/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ButtonModel;

/**
 *
 * @author alumnogreibd
 */
public class VAnular extends javax.swing.JFrame {

    private aplicacion.FachadaAplicacion fa;
    private java.awt.Frame parent;

    /**
     * Creates new form VMercado
     */
    public VAnular(aplicacion.FachadaAplicacion fa, java.awt.Frame parent) throws ParseException {
        this.fa = fa;
        this.parent = parent;
        initComponents();
        reservaP.setVisible(false);
        confirmar.setVisible(false);
        fallo.setVisible(false);
        fallocorreo.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        grupoBotones = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        panelFondo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        volver = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        correotxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        reservaP = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        id3 = new javax.swing.JTextField();
        res = new javax.swing.JTextField();
        id4 = new javax.swing.JTextField();
        id5 = new javax.swing.JTextField();
        id6 = new javax.swing.JTextField();
        id7 = new javax.swing.JTextField();
        correo = new javax.swing.JTextField();
        id9 = new javax.swing.JTextField();
        confirmar = new javax.swing.JButton();
        fallo = new javax.swing.JLabel();
        fallocorreo = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(390, 844));
        setResizable(false);
        setSize(new java.awt.Dimension(390, 844));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 714, 390, -1));

        panelFondo.setBackground(new java.awt.Color(255, 255, 255));
        panelFondo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        panelFondo.setPreferredSize(new java.awt.Dimension(390, 844));
        panelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Anular Billete");
        panelFondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

        volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/volver.png"))); // NOI18N
        volver.setBorderPainted(false);
        volver.setContentAreaFilled(false);
        volver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        volver.setFocusable(false);
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        panelFondo.add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 40, -1));

        jPanel2.setBackground(new java.awt.Color(1, 88, 122));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Correo:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 30));

        correotxt.setForeground(new java.awt.Color(1, 88, 122));
        jPanel2.add(correotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 170, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/buscar.png"))); // NOI18N
        jButton1.setText("Buscar Reserva");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 170, 40));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("ID de reserva:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        id.setForeground(new java.awt.Color(1, 88, 122));
        id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idKeyTyped(evt);
            }
        });
        jPanel2.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 170, -1));

        panelFondo.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 350, 190));

        reservaP.setBackground(new java.awt.Color(1, 88, 122));
        reservaP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID de reserva:");
        reservaP.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 30));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Día:");
        reservaP.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, 30));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Hora:");
        reservaP.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, 30));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nº Billetes:");
        reservaP.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, 30));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Correo:");
        reservaP.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, 30));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Nombre:");
        reservaP.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, 30));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Ruta:");
        reservaP.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, 30));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Importe Total:");
        reservaP.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, 20));

        id3.setEditable(false);
        id3.setBackground(new java.awt.Color(255, 255, 255));
        id3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        id3.setForeground(new java.awt.Color(1, 88, 122));
        id3.setText("110.40€");
        id3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                id3KeyTyped(evt);
            }
        });
        reservaP.add(id3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 190, -1));

        res.setEditable(false);
        res.setBackground(new java.awt.Color(255, 255, 255));
        res.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        res.setForeground(new java.awt.Color(1, 88, 122));
        res.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                resKeyTyped(evt);
            }
        });
        reservaP.add(res, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 14, 190, -1));

        id4.setEditable(false);
        id4.setBackground(new java.awt.Color(255, 255, 255));
        id4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        id4.setForeground(new java.awt.Color(1, 88, 122));
        id4.setText("Ruta por los cañones del Sil");
        id4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                id4KeyTyped(evt);
            }
        });
        reservaP.add(id4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 190, 30));

        id5.setEditable(false);
        id5.setBackground(new java.awt.Color(255, 255, 255));
        id5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        id5.setForeground(new java.awt.Color(1, 88, 122));
        id5.setText("14/12/2022");
        id5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id5ActionPerformed(evt);
            }
        });
        id5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                id5KeyTyped(evt);
            }
        });
        reservaP.add(id5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 190, -1));

        id6.setEditable(false);
        id6.setBackground(new java.awt.Color(255, 255, 255));
        id6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        id6.setForeground(new java.awt.Color(1, 88, 122));
        id6.setText("9:00");
        id6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                id6KeyTyped(evt);
            }
        });
        reservaP.add(id6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 190, -1));

        id7.setEditable(false);
        id7.setBackground(new java.awt.Color(255, 255, 255));
        id7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        id7.setForeground(new java.awt.Color(1, 88, 122));
        id7.setText("8");
        id7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                id7KeyTyped(evt);
            }
        });
        reservaP.add(id7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 190, -1));

        correo.setEditable(false);
        correo.setBackground(new java.awt.Color(255, 255, 255));
        correo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        correo.setForeground(new java.awt.Color(1, 88, 122));
        correo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                correoKeyTyped(evt);
            }
        });
        reservaP.add(correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 190, -1));

        id9.setEditable(false);
        id9.setBackground(new java.awt.Color(255, 255, 255));
        id9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        id9.setForeground(new java.awt.Color(1, 88, 122));
        id9.setText("Pablo Martínez González");
        id9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                id9KeyTyped(evt);
            }
        });
        reservaP.add(id9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 190, -1));

        panelFondo.add(reservaP, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 350, 350));

        confirmar.setBackground(new java.awt.Color(255, 255, 255));
        confirmar.setText("Confirmar Anulación");
        confirmar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(1, 88, 122), 2));
        confirmar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        confirmar.setFocusPainted(false);
        confirmar.setFocusable(false);
        confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarActionPerformed(evt);
            }
        });
        panelFondo.add(confirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 760, 180, 40));

        fallo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fallo.setText("<html>Lo sentimos, no hemos encontrado su reserva, compruebe los datos introducidos<html>");
        panelFondo.add(fallo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 300, 40));

        fallocorreo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fallocorreo.setForeground(new java.awt.Color(204, 0, 0));
        fallocorreo.setText("*Formato de correo inválido - xxx@xxx.xx*");
        panelFondo.add(fallocorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ayuda2.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setFocusPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panelFondo.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 750, 60, 60));

        getContentPane().add(panelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        // TODO add your handling code here:
        this.cerrar();
    }//GEN-LAST:event_volverActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (!correotxt.getText().isEmpty() && !id.getText().isEmpty()) {
            Pattern pattern = Pattern.compile("^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$");
            Matcher mather = pattern.matcher(correotxt.getText());
            if (mather.find() == false) {
                fallocorreo.setVisible(true);
                fallo.setVisible(false);
            } else {
                reservaP.setVisible(true);
                res.setText(id.getText());
                correo.setText(correotxt.getText());
                confirmar.setVisible(true);
                fallo.setVisible(false);
                fallocorreo.setVisible(false);
            }
        } else {
            fallocorreo.setVisible(false);
            fallo.setVisible(true);
            confirmar.setVisible(false);
            reservaP.setVisible(false);
        }


    }//GEN-LAST:event_jButton1ActionPerformed


    private void confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarActionPerformed
        // TODO add your handling code here:
        fa.muestraMensaje(this, "Su reserva ha sido cancelada correctamente");
        this.reservaP.setVisible(false);
        correotxt.setText("");
        id.setText("");
        confirmar.setVisible(false);
    }//GEN-LAST:event_confirmarActionPerformed

    private void idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_idKeyTyped

    private void resKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_resKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_resKeyTyped

    private void id3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_id3KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_id3KeyTyped

    private void id4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_id4KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_id4KeyTyped

    private void id5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_id5KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_id5KeyTyped

    private void id6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_id6KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_id6KeyTyped

    private void id7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_id7KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_id7KeyTyped

    private void correoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_correoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_correoKeyTyped

    private void id9KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_id9KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_id9KeyTyped

    private void id5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        fa.vistaAyuda(this);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton confirmar;
    private javax.swing.JTextField correo;
    private javax.swing.JTextField correotxt;
    private javax.swing.JLabel fallo;
    private javax.swing.JLabel fallocorreo;
    private javax.swing.ButtonGroup grupoBotones;
    private javax.swing.JTextField id;
    private javax.swing.JTextField id3;
    private javax.swing.JTextField id4;
    private javax.swing.JTextField id5;
    private javax.swing.JTextField id6;
    private javax.swing.JTextField id7;
    private javax.swing.JTextField id9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JTextField res;
    private javax.swing.JPanel reservaP;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables

    public void cerrar() {
        this.dispose();
        this.parent.setVisible(true);
    }

}
