/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Color;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.ImageIcon;


/**
 *
 * @author alumnogreibd
 */
public class VAyuda extends javax.swing.JFrame {

    private aplicacion.FachadaAplicacion fa;
    private java.awt.Frame parent;
    /**
     * Creates new form VMercado
     */
    public VAyuda(aplicacion.FachadaAplicacion fa, java.awt.Frame parent) {
        this.fa = fa;
        this.parent = parent;
        initComponents();
        this.jScrollPane1.getVerticalScrollBar().setPreferredSize(new Dimension(13,HEIGHT));
        this.jScrollPane1.getVerticalScrollBar().setBackground(new Color(67,78,80));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        volver = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane3 = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextPane4 = new javax.swing.JTextPane();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextPane5 = new javax.swing.JTextPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextPane6 = new javax.swing.JTextPane();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextPane7 = new javax.swing.JTextPane();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextPane8 = new javax.swing.JTextPane();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTextPane9 = new javax.swing.JTextPane();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTextPane10 = new javax.swing.JTextPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(390, 844));
        setResizable(false);
        setSize(new java.awt.Dimension(390, 844));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 714, 390, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(390, 844));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Ayuda");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, -1, -1));

        volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/volver.png"))); // NOI18N
        volver.setBorderPainted(false);
        volver.setContentAreaFilled(false);
        volver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        volver.setFocusable(false);
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        jPanel3.add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 40, -1));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setEnabled(false);
        jPanel4.setRequestFocusEnabled(false);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(16, 137, 177));
        jLabel2.setText("1 -");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 680, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("<html> Para realizar la compra, se seguirán un total de 5 pasos consecutivos <html>");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 610, 318, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Inicio.png"))); // NOI18N
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/mapa.png"))); // NOI18N
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Mas.png"))); // NOI18N
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/billetes.png"))); // NOI18N
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jTextPane1.setEditable(false);
        jTextPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(16, 137, 177), 2));
        jTextPane1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextPane1.setText("Menú de opciones desde donde seleccionar el idioma, poder ver las formas de contacto o enviar un correo electrónico directamente.");
        jScrollPane2.setViewportView(jTextPane1);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, 270, 60));

        jTextPane2.setEditable(false);
        jTextPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(16, 137, 177), 2));
        jTextPane2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextPane2.setText("Página de Inicio - En ella se hace un breve resumen de la aplicación, mopstrando información acerca de la naviera.");
        jScrollPane3.setViewportView(jTextPane2);

        jPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 270, 60));

        jScrollPane4.setToolTipText("");

        jTextPane3.setEditable(false);
        jTextPane3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(16, 137, 177), 2));
        jTextPane3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextPane3.setText("En el caso de querer realizar una cancelación de una reserva, se podrá realizar utilizando el ID de reserva para buscarla, y posteriormente cancelándola directamente.");
        jScrollPane4.setViewportView(jTextPane3);

        jPanel4.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1200, 320, 80));

        jTextPane4.setEditable(false);
        jTextPane4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(16, 137, 177), 2));
        jTextPane4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextPane4.setText("Página desde la cual se podrá ver las distintas rutas que se ofrecen, así como un acceso directo a más información de cada una, pulsando dentro del recuadro de la ruta correspondiente.");
        jScrollPane5.setViewportView(jTextPane4);

        jPanel4.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 270, 90));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(16, 137, 177));
        jLabel9.setText("Funciones básicas");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("<html> Esta aplicación sobre la reserva de rutas fluviales por el río Miño y por los cañones del Sil, cuenta con todo lo necesario para que pueda manejar la compra de billetes, así como consultar información, de manera sencilla y rápida. <html>");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 318, 86));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(16, 137, 177));
        jLabel11.setText("Cancelación de Reservas");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 1150, -1, -1));

        jTextPane5.setEditable(false);
        jTextPane5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(16, 137, 177), 2));
        jTextPane5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextPane5.setText("Acceso desde el menú para realizar las acciones de compra de billetes de rutas, o bien de su cancelación");
        jScrollPane6.setViewportView(jTextPane5);

        jPanel4.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 270, 60));

        jTextPane6.setEditable(false);
        jTextPane6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(16, 137, 177), 2));
        jTextPane6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextPane6.setText("Selección del número de entradas a reservar, tanto en el caso de individuales como de grupo.\nAdemás, se puede indicar otras características como la necesidad de guía o adaptación a movilidad reducida.\nEn esta pantalla se podrá ver el importe total que supondrá la reserva.");
        jScrollPane7.setViewportView(jTextPane6);

        jPanel4.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 740, 270, 130));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(16, 137, 177));
        jLabel12.setText("2 -");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 780, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(16, 137, 177));
        jLabel13.setText("3 -");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 890, -1, 30));

        jTextPane7.setEditable(false);
        jTextPane7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(16, 137, 177), 2));
        jTextPane7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextPane7.setText("Introducción de los datos personales de la persona que realiza la reserva.");
        jScrollPane8.setViewportView(jTextPane7);

        jPanel4.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 880, 270, 50));

        jTextPane8.setEditable(false);
        jTextPane8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(16, 137, 177), 2));
        jTextPane8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextPane8.setText("Inserción de datos bancarios para la realización del pago.");
        jScrollPane9.setViewportView(jTextPane8);

        jPanel4.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 960, 270, 40));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(16, 137, 177));
        jLabel14.setText("4 -");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 960, -1, 30));

        jTextPane9.setEditable(false);
        jTextPane9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(16, 137, 177), 2));
        jTextPane9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextPane9.setText("Consulta del resumen de la reserva y pago formalizados, obteniendo el ID de la reserva, el cual servirá para el día de la ruta, o para realizar cancelaciones del viaje.\nEn caso de ser necesario, se podrá imprimir la reserva.");
        jScrollPane10.setViewportView(jTextPane9);

        jPanel4.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 1020, 270, 100));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(16, 137, 177));
        jLabel15.setText("5 -");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1050, -1, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(16, 137, 177));
        jLabel16.setText("Proceso de Compra");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, -1, -1));

        jTextPane10.setEditable(false);
        jTextPane10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(16, 137, 177), 2));
        jTextPane10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextPane10.setText("Selección de la ruta a realizar, la fecha de la reserva, y la hora de partida, así como indicar si son billetes individuales o de grupo.");
        jScrollPane11.setViewportView(jTextPane10);

        jPanel4.add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 660, 270, 60));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 1280, 240, 30));

        jScrollPane1.setViewportView(jPanel4);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 390, 620));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tripulacion.png"))); // NOI18N
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, -1, 140));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        // TODO add your handling code here:
        this.dispose();
        this.parent.setVisible(true);
    }//GEN-LAST:event_volverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane10;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JTextPane jTextPane3;
    private javax.swing.JTextPane jTextPane4;
    private javax.swing.JTextPane jTextPane5;
    private javax.swing.JTextPane jTextPane6;
    private javax.swing.JTextPane jTextPane7;
    private javax.swing.JTextPane jTextPane8;
    private javax.swing.JTextPane jTextPane9;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables

    
}
