/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import aplicacion.Reserva;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ButtonModel;

/**
 *
 * @author alumnogreibd
 */
public class VCompra extends javax.swing.JFrame {

    private aplicacion.FachadaAplicacion fa;
    private java.awt.Frame parent;
    private Reserva reserva;

    /**
     * Creates new form VMercado
     */
    public VCompra(aplicacion.FachadaAplicacion fa, java.awt.Frame parent, Reserva res) {
        this.fa = fa;
        this.parent = parent;
        this.reserva = res;
        initComponents();

        ruta.setText(" " + reserva.getRuta());
        dia.setText(" " + reserva.getFecha());
        hora.setText(" " + reserva.getHora());
        num.setText(" " + reserva.getBilletes());
        DecimalFormat df = new DecimalFormat("#.00");
        imp.setText(" " + df.format(reserva.getImporte()) + "€");
        if (reserva.isGuia()) {
            guia.setText(" Si");
        } else {
            guia.setText(" No");
        }
        if (reserva.isMovRed()) {
            mov.setText(" Si");
        } else {
            mov.setText(" No");
        }
        falloNombre.setVisible(false);
        falloapellidos.setVisible(false);
        falloPostal.setVisible(false);
        fallodni.setVisible(false);
        fallocorreo.setVisible(false);
        fallotelefono.setVisible(false);
        

    }

    VCompra() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        grupoBotones = new javax.swing.ButtonGroup();
        jProgressBar1 = new javax.swing.JProgressBar();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        cerrar = new javax.swing.JButton();
        volver = new javax.swing.JButton();
        pagar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtHora = new javax.swing.JLabel();
        txtRuta = new javax.swing.JLabel();
        txtImporte = new javax.swing.JLabel();
        txtDia = new javax.swing.JLabel();
        txtBilletes = new javax.swing.JLabel();
        txtGuia1 = new javax.swing.JLabel();
        ruta = new javax.swing.JLabel();
        dia = new javax.swing.JLabel();
        guia = new javax.swing.JLabel();
        num = new javax.swing.JLabel();
        txtGuia2 = new javax.swing.JLabel();
        hora = new javax.swing.JLabel();
        mov = new javax.swing.JLabel();
        imp = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtapellidos = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtpostal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        dni = new javax.swing.JTextField();
        correo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        telefono = new javax.swing.JTextField();
        fallotelefono = new javax.swing.JLabel();
        falloNombre = new javax.swing.JLabel();
        falloapellidos = new javax.swing.JLabel();
        falloPostal = new javax.swing.JLabel();
        fallodni = new javax.swing.JLabel();
        fallocorreo = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(390, 844));
        setResizable(false);
        setSize(new java.awt.Dimension(390, 844));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 714, 390, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel3.setPreferredSize(new java.awt.Dimension(390, 844));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cerrar.png"))); // NOI18N
        cerrar.setBorderPainted(false);
        cerrar.setContentAreaFilled(false);
        cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cerrar.setFocusable(false);
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });
        jPanel3.add(cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 40, 30));

        volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/volver.png"))); // NOI18N
        volver.setBorderPainted(false);
        volver.setContentAreaFilled(false);
        volver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        volver.setFocusable(false);
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        jPanel3.add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 40, -1));

        pagar.setBackground(new java.awt.Color(1, 88, 122));
        pagar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        pagar.setForeground(new java.awt.Color(255, 255, 255));
        pagar.setText("Comprar");
        pagar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pagar.setFocusPainted(false);
        pagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagarActionPerformed(evt);
            }
        });
        jPanel3.add(pagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 780, 140, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Datos de Compra");
        jLabel2.setName(""); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 210, 30));

        jPanel2.setBackground(new java.awt.Color(1, 88, 122));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtHora.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtHora.setForeground(new java.awt.Color(255, 255, 255));
        txtHora.setText("Hora:");
        jPanel2.add(txtHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, -1, -1));

        txtRuta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtRuta.setForeground(new java.awt.Color(255, 255, 255));
        txtRuta.setText("Ruta: ");
        jPanel2.add(txtRuta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        txtImporte.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtImporte.setForeground(new java.awt.Color(255, 255, 255));
        txtImporte.setText("Importe:");
        jPanel2.add(txtImporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, -1, -1));

        txtDia.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtDia.setForeground(new java.awt.Color(255, 255, 255));
        txtDia.setText("Día:");
        jPanel2.add(txtDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 40, -1));

        txtBilletes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtBilletes.setForeground(new java.awt.Color(255, 255, 255));
        txtBilletes.setText("Nº Billetes:");
        jPanel2.add(txtBilletes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        txtGuia1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtGuia1.setForeground(new java.awt.Color(255, 255, 255));
        txtGuia1.setText("Guía incluido:");
        jPanel2.add(txtGuia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        ruta.setBackground(new java.awt.Color(255, 255, 255));
        ruta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ruta.setText("-");
        ruta.setOpaque(true);
        jPanel2.add(ruta, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 260, -1));

        dia.setBackground(new java.awt.Color(255, 255, 255));
        dia.setText("-");
        dia.setOpaque(true);
        jPanel2.add(dia, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 100, -1));

        guia.setBackground(new java.awt.Color(255, 255, 255));
        guia.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        guia.setText("-");
        guia.setOpaque(true);
        jPanel2.add(guia, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 40, -1));

        num.setBackground(new java.awt.Color(255, 255, 255));
        num.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        num.setText("-");
        num.setOpaque(true);
        jPanel2.add(num, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 50, -1));

        txtGuia2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtGuia2.setForeground(new java.awt.Color(255, 255, 255));
        txtGuia2.setText("Mov. Red.:");
        jPanel2.add(txtGuia2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, -1, -1));

        hora.setBackground(new java.awt.Color(255, 255, 255));
        hora.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        hora.setText("-");
        hora.setOpaque(true);
        jPanel2.add(hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 90, -1));

        mov.setBackground(new java.awt.Color(255, 255, 255));
        mov.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mov.setText("-");
        mov.setOpaque(true);
        jPanel2.add(mov, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 40, -1));

        imp.setBackground(new java.awt.Color(255, 255, 255));
        imp.setText("-");
        imp.setOpaque(true);
        jPanel2.add(imp, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 70, -1));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 350, 150));

        txtnombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtnombre.setForeground(new java.awt.Color(16, 137, 177));
        txtnombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(1, 88, 122), 2));
        jPanel3.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 250, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Nombre");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Apellidos");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, 30));

        txtapellidos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtapellidos.setForeground(new java.awt.Color(16, 137, 177));
        txtapellidos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(1, 88, 122), 2));
        jPanel3.add(txtapellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 250, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Código Postal");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 180, 30));

        txtpostal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtpostal.setForeground(new java.awt.Color(16, 137, 177));
        txtpostal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(1, 88, 122), 2));
        jPanel3.add(txtpostal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 250, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("DNI");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 180, 30));

        dni.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dni.setForeground(new java.awt.Color(16, 137, 177));
        dni.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(1, 88, 122), 2));
        jPanel3.add(dni, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, 140, 30));

        correo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        correo.setForeground(new java.awt.Color(16, 137, 177));
        correo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(1, 88, 122), 2));
        jPanel3.add(correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 630, 250, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Dirección de correo");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 600, 180, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Teléfono");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 680, 180, 30));

        telefono.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        telefono.setForeground(new java.awt.Color(16, 137, 177));
        telefono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(1, 88, 122), 2));
        jPanel3.add(telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 710, 210, 30));

        fallotelefono.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fallotelefono.setForeground(new java.awt.Color(194, 0, 0));
        fallotelefono.setText("*Formato teléfono incorrecto - (+34|34) 645765123 *");
        jPanel3.add(fallotelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 740, -1, 20));

        falloNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        falloNombre.setForeground(new java.awt.Color(194, 0, 0));
        falloNombre.setText("*Formato de nombre incorrecto - xxxx*");
        jPanel3.add(falloNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, 20));

        falloapellidos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        falloapellidos.setForeground(new java.awt.Color(194, 0, 0));
        falloapellidos.setText("*Formato de apellidos incorrecto - xxx (-xxx/ xxx)*");
        jPanel3.add(falloapellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, 20));

        falloPostal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        falloPostal.setForeground(new java.awt.Color(194, 0, 0));
        falloPostal.setText("*Formato de código postal  incorrecto - 13456*");
        jPanel3.add(falloPostal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, -1, 20));

        fallodni.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fallodni.setForeground(new java.awt.Color(194, 0, 0));
        fallodni.setText("*Formato de DNI incorrecto - 111111111A*");
        jPanel3.add(fallodni, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, -1, 20));

        fallocorreo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fallocorreo.setForeground(new java.awt.Color(194, 0, 0));
        fallocorreo.setText("*Formato de correo incorrecto - xxx@xxx.xx *");
        jPanel3.add(fallocorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 660, -1, 20));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("_____________________________________\n");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 340, 20));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ayuda2.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setFocusPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 770, 60, 60));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
        // TODO add your handling code here:
        fa.muestraCancelar(this);
    }//GEN-LAST:event_cerrarActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        // TODO add your handling code here:
        this.dispose();
        parent.setVisible(true);
    }//GEN-LAST:event_volverActionPerformed

    private void pagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagarActionPerformed
        // TODO add your handling code here:
        comprobaciones();

    }//GEN-LAST:event_pagarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        fa.vistaAyuda(this);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed
    private boolean nombre() {
        Pattern pat = Pattern.compile("^[a-zA-ZñÑáéíóúÁÉÍÓÚüÜ]{2,16}$");
        Matcher mat = pat.matcher(txtnombre.getText());

        return !mat.matches();
    }

    private boolean apellidos() {
        Pattern pat = Pattern.compile("^[a-zA-ZñÑáéíóúÁÉÍÓÚüÜ-]+([ '-][a-zA-ZZñÑáéíóúÁÉÍÓÚüÜ]+)*");
        Matcher mat = pat.matcher(txtapellidos.getText());

        return !mat.matches();
    }

    private boolean codPostal() {
        boolean estado = false;
        Pattern pat = Pattern.compile("^[0-9]{5}$");
        Matcher mat = pat.matcher(txtpostal.getText());

        return !mat.matches();
    }

    private boolean dni() {

        final String dniChars = "TRWAGMYFPDXBNJZSQVHLCKEabcdefghijklmnopqrstuvwxyz";
        String d = dni.getText();

        if (d.length() == 9 && !d.contains(" ")) {
            String intPartDNI = d.trim().substring(0, 7);
            String ltrDNI = "" + d.charAt(8);
            try {
                Integer.parseInt(intPartDNI);
            } catch (NumberFormatException excepcion) {
                return false;
            }

            return dniChars.contains(ltrDNI);
        } else {
            return false;
        }
    }

    private boolean correo() {

        Pattern pattern = Pattern.compile("^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$");
        Matcher mather = pattern.matcher(correo.getText());
        return mather.find() == false;
    }
    private boolean telefono() {

        Pattern pattern = Pattern.compile("^(\\+34|0034|34)?[6789]\\d{8}$");
        Matcher mather = pattern.matcher(telefono.getText());
        return mather.find() == false;
    }

    private void comprobaciones() {
        boolean ok = true;
        if (nombre()) {
            falloNombre.setVisible(true);
            ok = false;
        } else {
            falloNombre.setVisible(false);
            
        }
        if (apellidos()) {
            falloapellidos.setVisible(true);
            ok = false;
        } else {
            falloapellidos.setVisible(false);
            
        }
        if (codPostal()) {
            falloPostal.setVisible(true);
            ok = false;
        } else {
            falloPostal.setVisible(false);
        }
        if (dni()) {
            fallodni.setVisible(false);

        } else {
            fallodni.setVisible(true);
            ok = false;
        }
        if (correo()) {
            fallocorreo.setVisible(true);
            ok = false;

        } else {
            fallocorreo.setVisible(false);
        }
        if (telefono()) {
            fallotelefono.setVisible(true);
            ok = false;

        } else {
            fallotelefono.setVisible(false);
        }
        if(ok){
            reserva.setNombre(txtnombre.getText()+" "+txtapellidos.getText());
            reserva.setCodPostal(txtpostal.getText());
            reserva.setDni(dni.getText());
            reserva.setCorreo(correo.getText());
            reserva.setTelefono(telefono.getText());
            fa.vistaPago(this,reserva);
            this.setVisible(false);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cerrar;
    private javax.swing.JTextField correo;
    private javax.swing.JLabel dia;
    private javax.swing.JTextField dni;
    private javax.swing.JLabel falloNombre;
    private javax.swing.JLabel falloPostal;
    private javax.swing.JLabel falloapellidos;
    private javax.swing.JLabel fallocorreo;
    private javax.swing.JLabel fallodni;
    private javax.swing.JLabel fallotelefono;
    private javax.swing.ButtonGroup grupoBotones;
    private javax.swing.JLabel guia;
    private javax.swing.JLabel hora;
    private javax.swing.JLabel imp;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel mov;
    private javax.swing.JLabel num;
    private javax.swing.JButton pagar;
    private javax.swing.JLabel ruta;
    private javax.swing.JTextField telefono;
    private javax.swing.JLabel txtBilletes;
    private javax.swing.JLabel txtDia;
    private javax.swing.JLabel txtGuia1;
    private javax.swing.JLabel txtGuia2;
    private javax.swing.JLabel txtHora;
    private javax.swing.JLabel txtImporte;
    private javax.swing.JLabel txtRuta;
    private javax.swing.JTextField txtapellidos;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtpostal;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables

    public void cerrar() {
        this.dispose();
        VIndividual vi = new VIndividual();
        VGrupo vg = new VGrupo();
        if(this.parent.getClass().equals(vi.getClass())){
            vi = (VIndividual) parent;
            vi.cerrar();
        }else if(this.parent.getClass().equals(vg.getClass())){
            vg = (VGrupo) parent;
            vg.cerrar();
        }
    }

    public void confirmacionSalir(boolean dec) {
        if (dec) {
            this.cerrar();
        }
    }
}
