/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import aplicacion.Reserva;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.util.Date;

/**
 *
 * @author alumnogreibd
 */
public class VGrupo extends javax.swing.JFrame {

    private aplicacion.FachadaAplicacion fa;
    private java.awt.Frame parent;
    private Double precioGr;
    private Double precioGuia;
    private Double precioTotal;
    private Reserva reserva;

    /**
     * Creates new form VMercado
     */
    public VGrupo(aplicacion.FachadaAplicacion fa, java.awt.Frame parent, Reserva res, Double precRuta) throws ParseException {
        this.fa = fa;
        this.parent = parent;
        this.reserva = res;
        initComponents();

        precioGr = 10 + precRuta;
        precioGuia = 20.0;
        precioTotal = precioGr * 10.0;
        ruta.setText(" " + res.getRuta());
        dia.setText(" " + res.getFecha());
        hora.setText(" " + res.getHora());

        precGr.setText(precioGr + "€");
        precGuia.setText(precioGuia + "€");
        precTotal.setText(precioTotal.toString() + "€");
        
        idioma.setEnabled(false);
        calculaTotal();
    }

    VGrupo() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        grupoBotones = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        cerrar = new javax.swing.JButton();
        volver = new javax.swing.JButton();
        comprar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtHora = new javax.swing.JLabel();
        txtRuta = new javax.swing.JLabel();
        txtDia = new javax.swing.JLabel();
        ruta = new javax.swing.JLabel();
        dia = new javax.swing.JLabel();
        hora = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        masSe = new javax.swing.JLabel();
        menosSe = new javax.swing.JLabel();
        movRed = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        precTotal = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        guia = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        idioma = new javax.swing.JComboBox<>();
        precGuia = new javax.swing.JLabel();
        precGr = new javax.swing.JLabel();
        numE = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(390, 844));
        setResizable(false);
        setSize(new java.awt.Dimension(390, 844));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 714, 390, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel3.setPreferredSize(new java.awt.Dimension(390, 844));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cerrar.png"))); // NOI18N
        cerrar.setBorderPainted(false);
        cerrar.setContentAreaFilled(false);
        cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cerrar.setFocusable(false);
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });
        jPanel3.add(cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 40, -1));

        volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/volver.png"))); // NOI18N
        volver.setBorderPainted(false);
        volver.setContentAreaFilled(false);
        volver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        volver.setFocusable(false);
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        jPanel3.add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 40, -1));

        comprar.setBackground(new java.awt.Color(1, 88, 122));
        comprar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        comprar.setForeground(new java.awt.Color(255, 255, 255));
        comprar.setText("Comprar");
        comprar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        comprar.setFocusPainted(false);
        comprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprarActionPerformed(evt);
            }
        });
        jPanel3.add(comprar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 770, 140, 40));

        jPanel2.setBackground(new java.awt.Color(1, 88, 122));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtHora.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtHora.setForeground(new java.awt.Color(255, 255, 255));
        txtHora.setText("Hora:");
        jPanel2.add(txtHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        txtRuta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtRuta.setForeground(new java.awt.Color(255, 255, 255));
        txtRuta.setText("Ruta: ");
        jPanel2.add(txtRuta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        txtDia.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtDia.setForeground(new java.awt.Color(255, 255, 255));
        txtDia.setText("Día:");
        jPanel2.add(txtDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        ruta.setBackground(new java.awt.Color(255, 255, 255));
        ruta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ruta.setText("-");
        ruta.setOpaque(true);
        jPanel2.add(ruta, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 230, -1));

        dia.setBackground(new java.awt.Color(255, 255, 255));
        dia.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dia.setText("-");
        dia.setOpaque(true);
        jPanel2.add(dia, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 230, -1));

        hora.setBackground(new java.awt.Color(255, 255, 255));
        hora.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        hora.setText("-");
        hora.setOpaque(true);
        jPanel2.add(hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 230, -1));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 350, 160));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Atención de movilidad reducida");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, -1, 30));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel22.setText("Tamaño del grupo");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        masSe.setBackground(new java.awt.Color(255, 222, 117));
        masSe.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        masSe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        masSe.setText("+");
        masSe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(1, 88, 122), 2));
        masSe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        masSe.setOpaque(true);
        masSe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                masSeMouseClicked(evt);
            }
        });
        jPanel3.add(masSe, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 370, 30, 30));

        menosSe.setBackground(new java.awt.Color(255, 222, 117));
        menosSe.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        menosSe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menosSe.setText("-");
        menosSe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(1, 88, 122), 2));
        menosSe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menosSe.setOpaque(true);
        menosSe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menosSeMouseClicked(evt);
            }
        });
        jPanel3.add(menosSe, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, 30, 30));

        movRed.setBackground(new java.awt.Color(1, 88, 122));
        movRed.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        movRed.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        movRed.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        movRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movRedActionPerformed(evt);
            }
        });
        jPanel3.add(movRed, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 520, 30, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel9.setText("Importe Total:");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 710, -1, -1));

        precTotal.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        precTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        precTotal.setText("-");
        jPanel3.add(precTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 700, 100, 40));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Tarifa de grupo:");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Idioma del guía");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 620, -1, 30));

        guia.setBackground(new java.awt.Color(1, 88, 122));
        guia.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        guia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        guia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guia.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        guia.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                guiaStateChanged(evt);
            }
        });
        guia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guiaMouseClicked(evt);
            }
        });
        guia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guiaActionPerformed(evt);
            }
        });
        jPanel3.add(guia, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 570, 30, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Incluír guía");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 570, -1, 30));

        idioma.setBackground(new java.awt.Color(1, 88, 122));
        idioma.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        idioma.setForeground(new java.awt.Color(255, 255, 255));
        idioma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Español", "Ingés", "Gallego", "Francés", "Alemán" }));
        idioma.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        idioma.setRequestFocusEnabled(false);
        jPanel3.add(idioma, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 620, 130, 30));

        precGuia.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        precGuia.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        precGuia.setText("-");
        jPanel3.add(precGuia, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 570, 70, 30));

        precGr.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        precGr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        precGr.setText("-");
        jPanel3.add(precGr, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 50, -1));

        numE.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        numE.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        numE.setText("10");
        numE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(1, 88, 122), 2));
        numE.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                numEFocusLost(evt);
            }
        });
        numE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                numEMouseExited(evt);
            }
        });
        jPanel3.add(numE, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, 30, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("de Grupo");
        jLabel1.setName(""); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 190, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Compra Billetes");
        jLabel2.setName(""); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 190, 40));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("_____________________________________\n");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 340, 20));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/dis.png"))); // NOI18N
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 520, 30, 30));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ayuda2.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setFocusPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 760, 60, 60));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
        // TODO add your handling code here:
        fa.muestraCancelar(this);
    }//GEN-LAST:event_cerrarActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        // TODO add your handling code here:
        this.dispose();
        parent.setVisible(true);
    }//GEN-LAST:event_volverActionPerformed

    private void comprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprarActionPerformed
        // TODO add your handling code here:
        comprar();
    }//GEN-LAST:event_comprarActionPerformed

    private void movRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movRedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_movRedActionPerformed

    private void masSeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masSeMouseClicked
        // TODO add your handling code here:

        Integer numEntradas = Integer.parseInt(numE.getText()) + 1;
        if (numEntradas <= 50) {
            numE.setText(numEntradas.toString());
            precioTotal = precioTotal + precioGr;
            DecimalFormat df = new DecimalFormat("#.00");
            precTotal.setText(df.format(precioTotal) + "€");
        }
    }//GEN-LAST:event_masSeMouseClicked

    private void menosSeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menosSeMouseClicked
        // TODO add your handling code here:
        Integer numEntradas = Integer.parseInt(numE.getText());
        if (numEntradas > 10) {
            numEntradas -= 1;
            numE.setText(numEntradas.toString());
            precioTotal = precioTotal - precioGr;

            DecimalFormat df = new DecimalFormat("#.00");
            precTotal.setText(df.format(precioTotal) + "€");
        }
    }//GEN-LAST:event_menosSeMouseClicked

    private void calculaTotal() {
        precioTotal = 0.0;

        double numEntradas = Double.parseDouble(numE.getText());
        precioTotal = precioTotal + (precioGr * numEntradas);
        if (guia.isSelected()) {
            precioTotal += precioGuia;
        }
        DecimalFormat df = new DecimalFormat("#.00");
        precTotal.setText(df.format(precioTotal) + "€");
    }

    private void guiaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_guiaStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_guiaStateChanged

    private void guiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guiaMouseClicked
        // TODO add your handling code here:
        double numEntradas = Double.parseDouble(numE.getText());
        precioTotal = precioGr * numEntradas;
        if (guia.isSelected()) {
            precioTotal += precioGuia;
            idioma.setEnabled(true);
        } else {
            idioma.setEnabled(false);
        }
        DecimalFormat df = new DecimalFormat("#.00");
        precTotal.setText(df.format(precioTotal) + "€");
    }//GEN-LAST:event_guiaMouseClicked

    private void numEFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numEFocusLost
        // TODO add your handling code here:
        int numEntradas;
        try {
            Integer.parseInt(numE.getText());
        } catch (NumberFormatException excepcion) {
            numE.setText("0");
        }
        numEntradas = Integer.parseInt(numE.getText());
        if (numEntradas > 50) {
            numEntradas = 50;
            numE.setText(""+numEntradas);
        }
        if (numEntradas < 10) {
            numEntradas = 10;
            numE.setText(""+numEntradas);
        }
        precioTotal = precioGr * (double)numEntradas;
        if (guia.isSelected()) {
            precioTotal += precioGuia;
        }
        DecimalFormat df = new DecimalFormat("#.00");
        precTotal.setText(df.format(precioTotal) + "€");
    }//GEN-LAST:event_numEFocusLost

    private void numEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numEMouseExited
        // TODO add your handling code here:
        // TODO add your handling code here:
        int numEntradas;
        try {
            Integer.parseInt(numE.getText());
        } catch (NumberFormatException excepcion) {
            numE.setText("0");
        }
        numEntradas = Integer.parseInt(numE.getText());

        if (numEntradas > 50) {
            numEntradas = 50;
            numE.setText(""+numEntradas);
        }
        if (numEntradas < 10) {
            numEntradas = 10;
            numE.setText(""+numEntradas);
        }
        precioTotal = precioGr * (double)numEntradas;
        if (guia.isSelected()) {
            precioTotal += precioGuia;
        }
        DecimalFormat df = new DecimalFormat("#.00");
        precTotal.setText(df.format(precioTotal) + "€");

    }//GEN-LAST:event_numEMouseExited

    private void guiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guiaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        fa.vistaAyuda(this);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cerrar;
    private javax.swing.JButton comprar;
    private javax.swing.JLabel dia;
    private javax.swing.ButtonGroup grupoBotones;
    private javax.swing.JCheckBox guia;
    private javax.swing.JLabel hora;
    private javax.swing.JComboBox<String> idioma;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel masSe;
    private javax.swing.JLabel menosSe;
    private javax.swing.JCheckBox movRed;
    private javax.swing.JTextField numE;
    private javax.swing.JLabel precGr;
    private javax.swing.JLabel precGuia;
    private javax.swing.JLabel precTotal;
    private javax.swing.JLabel ruta;
    private javax.swing.JLabel txtDia;
    private javax.swing.JLabel txtHora;
    private javax.swing.JLabel txtRuta;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables

    public void cerrar() {
        this.dispose();
        VSeleccion vs = (VSeleccion) parent;
        vs.cerrar();
    }

    public void confirmacionSalir(boolean dec) {
        if (dec) {
            this.cerrar();
        }
    }

    private void comprar() {

        reserva.setBilletes(Integer.parseInt(numE.getText()));
        reserva.setImporte(precioTotal);
        reserva.setMovRed(movRed.isSelected());
        if (guia.isSelected()) {
            reserva.setGuia(guia.isSelected());
            reserva.setIdiomaG(idioma.getSelectedItem().toString());
        }

        fa.vistaCompra(this, reserva);
        this.setVisible(false);
    }

    public void confirmacionEdad(boolean confirmacion) {
        if (confirmacion) {
            comprar();
        }
    }
}
