/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import aplicacion.Reserva;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonModel;

/**
 *
 * @author alumnogreibd
 */
public class VIndividual extends javax.swing.JFrame {

    private aplicacion.FachadaAplicacion fa;
    private java.awt.Frame parent;
    private Double precioOrd;
    private Double precioBb;
    private Double precioNi;
    private Double precioEs;
    private Double precioSe;
    private Double precioTotal;
    private int numTotal;
    private Reserva reserva;

    /**
     * Creates new form VMercado
     */
    public VIndividual(aplicacion.FachadaAplicacion fa, java.awt.Frame parent, Reserva res, Double precRuta
    ) throws ParseException {
        this.fa = fa;
        this.parent = parent;
        this.reserva = res;
        initComponents();

        precioOrd = precRuta + 17.0;
        precioBb = 0.0;
        precioNi = 10.0 + precRuta;
        precioEs = 13.0 + precRuta;
        precioSe = 10.0 + precRuta;
        precioTotal = 0.0;
        numTotal = 0;
        ruta.setText("  " + reserva.getRuta());
        dia.setText("  " + reserva.getFecha());
        hora.setText("  " + reserva.getHora());

        precOrd.setText(precioOrd + "€");
        precBb.setText(precioBb + "€");
        precNi.setText(precioNi + "€");
        precEs.setText(precioEs + "€");
        precSe.setText(precioSe + "€");
        calculaTotal();
        numMax.setVisible(false);
    }

    VIndividual() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        grupoBotones = new javax.swing.ButtonGroup();
        jProgressBar1 = new javax.swing.JProgressBar();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cerrar = new javax.swing.JButton();
        volver = new javax.swing.JButton();
        comprar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtHora = new javax.swing.JLabel();
        hora = new javax.swing.JLabel();
        txtDia = new javax.swing.JLabel();
        txtRuta1 = new javax.swing.JLabel();
        ruta = new javax.swing.JLabel();
        dia = new javax.swing.JLabel();
        menosOrd = new javax.swing.JLabel();
        masOrd = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        precOrd = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        precNi = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        precEs = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        precSe = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        precBb = new javax.swing.JLabel();
        masBb = new javax.swing.JLabel();
        menosBb = new javax.swing.JLabel();
        masNi = new javax.swing.JLabel();
        menosNin = new javax.swing.JLabel();
        masEs = new javax.swing.JLabel();
        menosEs = new javax.swing.JLabel();
        masSe = new javax.swing.JLabel();
        menosSe = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        movRed = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        precTotal = new javax.swing.JLabel();
        numMax = new javax.swing.JLabel();
        numSe = new javax.swing.JTextField();
        numOrd = new javax.swing.JTextField();
        numBb = new javax.swing.JTextField();
        numNi = new javax.swing.JTextField();
        numEs = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(390, 844));
        setResizable(false);
        setSize(new java.awt.Dimension(390, 844));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 714, 390, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel3.setPreferredSize(new java.awt.Dimension(390, 844));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Individuales");
        jLabel1.setName(""); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 190, 40));

        cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cerrar.png"))); // NOI18N
        cerrar.setBorderPainted(false);
        cerrar.setContentAreaFilled(false);
        cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cerrar.setFocusable(false);
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });
        jPanel3.add(cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 40, -1));

        volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/volver.png"))); // NOI18N
        volver.setBorderPainted(false);
        volver.setContentAreaFilled(false);
        volver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        volver.setFocusable(false);
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        jPanel3.add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 40, -1));

        comprar.setBackground(new java.awt.Color(1, 88, 122));
        comprar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        comprar.setForeground(new java.awt.Color(255, 255, 255));
        comprar.setText("Comprar");
        comprar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        comprar.setFocusPainted(false);
        comprar.setFocusable(false);
        comprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprarActionPerformed(evt);
            }
        });
        jPanel3.add(comprar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 770, 140, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Compra Billetes");
        jLabel2.setName(""); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 190, 40));

        jPanel2.setBackground(new java.awt.Color(1, 88, 122));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.setToolTipText("");
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtHora.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtHora.setForeground(new java.awt.Color(255, 255, 255));
        txtHora.setText("Hora:");
        jPanel2.add(txtHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        hora.setBackground(new java.awt.Color(255, 255, 255));
        hora.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        hora.setText("-");
        hora.setOpaque(true);
        jPanel2.add(hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 230, -1));

        txtDia.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtDia.setForeground(new java.awt.Color(255, 255, 255));
        txtDia.setText("Día:");
        jPanel2.add(txtDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        txtRuta1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtRuta1.setForeground(new java.awt.Color(255, 255, 255));
        txtRuta1.setText("Ruta: ");
        jPanel2.add(txtRuta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        ruta.setBackground(new java.awt.Color(255, 255, 255));
        ruta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ruta.setText("-");
        ruta.setOpaque(true);
        jPanel2.add(ruta, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 230, -1));

        dia.setBackground(new java.awt.Color(255, 255, 255));
        dia.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dia.setText("-");
        dia.setOpaque(true);
        jPanel2.add(dia, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 230, -1));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 350, 160));

        menosOrd.setBackground(new java.awt.Color(255, 222, 117));
        menosOrd.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        menosOrd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menosOrd.setText("-");
        menosOrd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(1, 88, 122), 2));
        menosOrd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menosOrd.setOpaque(true);
        menosOrd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menosOrdMouseClicked(evt);
            }
        });
        jPanel3.add(menosOrd, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 30, 30));

        masOrd.setBackground(new java.awt.Color(255, 222, 117));
        masOrd.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        masOrd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        masOrd.setText("+");
        masOrd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(1, 88, 122), 2));
        masOrd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        masOrd.setOpaque(true);
        masOrd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                masOrdMouseClicked(evt);
            }
        });
        jPanel3.add(masOrd, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, 30, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel6.setText("Billete Ordinario");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        precOrd.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        precOrd.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        precOrd.setText("-");
        jPanel3.add(precOrd, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 50, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Atención de movilidad reducida");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 660, -1, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel8.setText("Niños");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, -1, -1));

        precNi.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        precNi.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        precNi.setText("-");
        jPanel3.add(precNi, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, 60, 30));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel18.setText("Estudiantes");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, -1, -1));

        precEs.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        precEs.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        precEs.setText("-");
        jPanel3.add(precEs, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 500, 60, 30));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel22.setText("Seniors");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, -1, -1));

        precSe.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        precSe.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        precSe.setText("-");
        jPanel3.add(precSe, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 560, 60, 30));

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel26.setText("Bebés");
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 140, -1));

        precBb.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        precBb.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        precBb.setText("-");
        jPanel3.add(precBb, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 60, 30));

        masBb.setBackground(new java.awt.Color(255, 222, 117));
        masBb.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        masBb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        masBb.setText("+");
        masBb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(1, 88, 122), 2));
        masBb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        masBb.setOpaque(true);
        masBb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                masBbMouseClicked(evt);
            }
        });
        jPanel3.add(masBb, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, 30, 30));

        menosBb.setBackground(new java.awt.Color(255, 222, 117));
        menosBb.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        menosBb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menosBb.setText("-");
        menosBb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(1, 88, 122), 2));
        menosBb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menosBb.setOpaque(true);
        menosBb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menosBbMouseClicked(evt);
            }
        });
        jPanel3.add(menosBb, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 380, 30, 30));

        masNi.setBackground(new java.awt.Color(255, 222, 117));
        masNi.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        masNi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        masNi.setText("+");
        masNi.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(1, 88, 122), 2, true));
        masNi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        masNi.setOpaque(true);
        masNi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                masNiMouseClicked(evt);
            }
        });
        jPanel3.add(masNi, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 440, 30, 30));

        menosNin.setBackground(new java.awt.Color(255, 222, 117));
        menosNin.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        menosNin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menosNin.setText("-");
        menosNin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(1, 88, 122), 2));
        menosNin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menosNin.setOpaque(true);
        menosNin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menosNinMouseClicked(evt);
            }
        });
        jPanel3.add(menosNin, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 440, 30, 30));

        masEs.setBackground(new java.awt.Color(255, 222, 117));
        masEs.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        masEs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        masEs.setText("+");
        masEs.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(1, 88, 122), 2));
        masEs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        masEs.setOpaque(true);
        masEs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                masEsMouseClicked(evt);
            }
        });
        jPanel3.add(masEs, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 500, 30, 30));

        menosEs.setBackground(new java.awt.Color(255, 222, 117));
        menosEs.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        menosEs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menosEs.setText("-");
        menosEs.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(1, 88, 122), 2));
        menosEs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menosEs.setOpaque(true);
        menosEs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menosEsMouseClicked(evt);
            }
        });
        jPanel3.add(menosEs, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 500, 30, 30));

        masSe.setBackground(new java.awt.Color(255, 222, 117));
        masSe.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        masSe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        masSe.setText("+");
        masSe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(1, 88, 122), 2));
        masSe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        masSe.setOpaque(true);
        masSe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                masSeMouseClicked(evt);
            }
        });
        jPanel3.add(masSe, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 560, 30, 30));

        menosSe.setBackground(new java.awt.Color(255, 222, 117));
        menosSe.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        menosSe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menosSe.setText("-");
        menosSe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(1, 88, 122), 2));
        menosSe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menosSe.setOpaque(true);
        menosSe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menosSeMouseClicked(evt);
            }
        });
        jPanel3.add(menosSe, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 560, 30, 30));

        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Mayores de 60 años");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, -1, -1));

        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Menores de 3 años");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, -1));

        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Entre 3 y 12 años ");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, -1, -1));

        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Carnet estudiante activo ");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, -1, -1));

        movRed.setBackground(new java.awt.Color(1, 88, 122));
        movRed.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        movRed.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        movRed.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(movRed, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 660, 30, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel9.setText("Importe Total:");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 720, -1, -1));

        precTotal.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        precTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        precTotal.setText("-");
        jPanel3.add(precTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 710, 100, 40));

        numMax.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        numMax.setText("*Número máximo de entradas: 10*");
        jPanel3.add(numMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 630, -1, -1));

        numSe.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        numSe.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        numSe.setText("0");
        numSe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(1, 88, 122), 2));
        numSe.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                numSeFocusLost(evt);
            }
        });
        numSe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                numSeMouseExited(evt);
            }
        });
        jPanel3.add(numSe, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 560, 30, 30));

        numOrd.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        numOrd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        numOrd.setText("0");
        numOrd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(1, 88, 122), 2));
        numOrd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                numOrdFocusLost(evt);
            }
        });
        numOrd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                numOrdMouseExited(evt);
            }
        });
        jPanel3.add(numOrd, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 30, 30));

        numBb.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        numBb.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        numBb.setText("0");
        numBb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(1, 88, 122), 2));
        numBb.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                numBbFocusLost(evt);
            }
        });
        numBb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                numBbMouseExited(evt);
            }
        });
        jPanel3.add(numBb, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, 30, 30));

        numNi.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        numNi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        numNi.setText("0");
        numNi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(1, 88, 122), 2));
        numNi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                numNiFocusLost(evt);
            }
        });
        numNi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                numNiMouseExited(evt);
            }
        });
        jPanel3.add(numNi, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 440, 30, 30));

        numEs.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        numEs.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        numEs.setText("0");
        numEs.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(1, 88, 122), 2, true));
        numEs.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                numEsFocusLost(evt);
            }
        });
        numEs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                numEsMouseExited(evt);
            }
        });
        jPanel3.add(numEs, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 500, 30, 30));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("_____________________________________\n");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 340, 20));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/dis.png"))); // NOI18N
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 660, 30, 30));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ayuda2.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setFocusPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 760, 60, 60));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
        // TODO add your handling code here:

        fa.muestraCancelar(this);
    }//GEN-LAST:event_cerrarActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        // TODO add your handling code here:
        this.dispose();
        parent.setVisible(true);
    }//GEN-LAST:event_volverActionPerformed

    private void comprar() {
        reserva.setBilletes(numTotal);
        reserva.setImporte(precioTotal);
        reserva.setMovRed(movRed.isSelected());
        this.setVisible(false);
        fa.vistaCompra(this, reserva);
    }
    private void comprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprarActionPerformed
        // TODO add your handling code here:
        if (numTotal > 0) {
            Integer numEntradasBb = Integer.parseInt(numBb.getText());
            Integer numEntradasNi = Integer.parseInt(numNi.getText());
            Integer numEntradasEs = Integer.parseInt(numEs.getText());
            if ((numEntradasBb + numEntradasNi) == numTotal) {
                fa.muestraMensaje(parent, "Los niños y bebes no pueden viajar solos.");
            } else if ((numEntradasBb + numEntradasNi + numEntradasEs) == numTotal) {
                fa.avisoEdad(this);
            } else {
                
                comprar();
            }
        } else {
            fa.muestraMensaje(parent, "Debe seleccionar al menos un billete.");
        }
    }//GEN-LAST:event_comprarActionPerformed

    private void masOrdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masOrdMouseClicked
        // TODO add your handling code here:
        Integer numEntradas = Integer.parseInt(numOrd.getText()) + 1;
        if ((numTotal + 1) <= 10) {
            numOrd.setText(numEntradas.toString());
            precioTotal = precioTotal + precioOrd;

            calculaTotal();
        } else {
            numMax.setVisible(true);
        }
    }//GEN-LAST:event_masOrdMouseClicked

    private void masBbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masBbMouseClicked
        // TODO add your handling code here:
        Integer numEntradas = Integer.parseInt(numBb.getText()) + 1;
        if ((numTotal + 1) <= 10) {
            numBb.setText(numEntradas.toString());
            precioTotal = precioTotal + precioBb;

            calculaTotal();
            numMax.setVisible(false);
        } else {
            numMax.setVisible(true);
        }
    }//GEN-LAST:event_masBbMouseClicked

    private void masNiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masNiMouseClicked
        // TODO add your handling code here:
        Integer numEntradas = Integer.parseInt(numNi.getText()) + 1;
        if ((numTotal + 1) <= 10) {
            numNi.setText(numEntradas.toString());
            precioTotal = precioTotal + precioNi;

            calculaTotal();
        } else {
            numMax.setVisible(true);
        }
    }//GEN-LAST:event_masNiMouseClicked

    private void masEsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masEsMouseClicked
        // TODO add your handling code here:
        Integer numEntradas = Integer.parseInt(numEs.getText()) + 1;
        if ((numTotal + 1) <= 10) {
            numEs.setText(numEntradas.toString());
            precioTotal = precioTotal + precioEs;
            calculaTotal();
        } else {
            numMax.setVisible(true);
        }
    }//GEN-LAST:event_masEsMouseClicked

    private void masSeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masSeMouseClicked
        // TODO add your handling code here:

        Integer numEntradas = Integer.parseInt(numSe.getText()) + 1;
        if ((numTotal + 1) <= 10) {
            numSe.setText(numEntradas.toString());
            precioTotal = precioTotal + precioSe;
            calculaTotal();
        }else {
            numMax.setVisible(true);
        }
    }//GEN-LAST:event_masSeMouseClicked

    private void menosOrdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menosOrdMouseClicked
        // TODO add your handling code here:
        Integer numEntradas = Integer.parseInt(numOrd.getText());
        if (numEntradas > 0) {
            numEntradas -= 1;
            numOrd.setText(numEntradas.toString());
            precioTotal = precioTotal - precioOrd;

            calculaTotal();
            numMax.setVisible(false);
        }

    }//GEN-LAST:event_menosOrdMouseClicked

    private void menosBbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menosBbMouseClicked
        // TODO add your handling code here:
        Integer numEntradas = Integer.parseInt(numBb.getText());
        if (numEntradas > 0) {
            numEntradas -= 1;
            numBb.setText(numEntradas.toString());
            precioTotal = precioTotal - precioBb;

            calculaTotal();
            numMax.setVisible(false);
        }
    }//GEN-LAST:event_menosBbMouseClicked

    private void menosNinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menosNinMouseClicked
        // TODO add your handling code here:
        Integer numEntradas = Integer.parseInt(numNi.getText());
        if (numEntradas > 0) {
            numEntradas -= 1;
            numNi.setText(numEntradas.toString());
            precioTotal = precioTotal - precioNi;

            calculaTotal();
            numMax.setVisible(false);
        }
    }//GEN-LAST:event_menosNinMouseClicked

    private void menosEsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menosEsMouseClicked
        // TODO add your handling code here:
        Integer numEntradas = Integer.parseInt(numEs.getText());
        if (numEntradas > 0) {
            numEntradas -= 1;
            numEs.setText(numEntradas.toString());
            precioTotal = precioTotal - precioEs;

            calculaTotal();
            numMax.setVisible(false);
        }
    }//GEN-LAST:event_menosEsMouseClicked

    private void menosSeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menosSeMouseClicked
        // TODO add your handling code here:
        Integer numEntradas = Integer.parseInt(numSe.getText());
        if (numEntradas > 0) {
            numEntradas -= 1;
            numSe.setText(numEntradas.toString());
            precioTotal = precioTotal - precioSe;
            calculaTotal();
            numMax.setVisible(false);
        }
    }//GEN-LAST:event_menosSeMouseClicked

    private void calculaTotal() {
        precioTotal = 0.0;
        numTotal = 0;
        double numEntradasOrd = Double.parseDouble(numOrd.getText());
        numTotal += numEntradasOrd;
        precioTotal = precioTotal + (precioOrd * numEntradasOrd);
        double numEntradasBb = Double.parseDouble(numBb.getText());
        numTotal += numEntradasBb;
        precioTotal = precioTotal + (precioBb * numEntradasBb);
        double numEntradasNi = Double.parseDouble(numNi.getText());
        numTotal += numEntradasNi;
        precioTotal = precioTotal + (precioNi * numEntradasNi);
        double numEntradasEs = Double.parseDouble(numEs.getText());
        numTotal += numEntradasEs;
        precioTotal = precioTotal + (precioEs * numEntradasEs);
        double numEntradasSe = Double.parseDouble(numSe.getText());
        numTotal += numEntradasSe;
        precioTotal = precioTotal + (precioSe * numEntradasSe);
        if (precioTotal == 0.0) {
            DecimalFormat df = new DecimalFormat("0.00");
            precTotal.setText(df.format(precioTotal) + "€");
        } else {
            DecimalFormat df = new DecimalFormat("#.00");
            precTotal.setText(df.format(precioTotal) + "€");
        }

    }


    private void numOrdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numOrdFocusLost
        // TODO add your handling code here:
        try {
            Integer numEntradasOrd = Integer.parseInt(numOrd.getText());
            Integer numEntradasBb = Integer.parseInt(numBb.getText());
            Integer numEntradasNi = Integer.parseInt(numNi.getText());
            Integer numEntradasEs = Integer.parseInt(numEs.getText());
            Integer numEntradasSe = Integer.parseInt(numSe.getText());
            calculaTotal();
            numOrd.setText(numEntradasOrd.toString());
            if (numEntradasOrd < 0) {

                numOrd.setText("0");
                calculaTotal();
            }

            if (numTotal > 10) {
                numTotal -= numEntradasOrd;
                numEntradasOrd = 0;
                while (numTotal < 10) {
                    numTotal += 1;
                    numEntradasOrd += 1;
                }
                numOrd.setText(numEntradasOrd.toString());
                calculaTotal();
            }
        } catch (NumberFormatException excepcion) {
            numOrd.setText("0");
            calculaTotal();
        }
    }//GEN-LAST:event_numOrdFocusLost

    private void numBbFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numBbFocusLost
        // TODO add your handling code here:
        try {
            Integer numEntradasOrd = Integer.parseInt(numOrd.getText());
            Integer numEntradasBb = Integer.parseInt(numBb.getText());
            Integer numEntradasNi = Integer.parseInt(numNi.getText());
            Integer numEntradasEs = Integer.parseInt(numEs.getText());
            Integer numEntradasSe = Integer.parseInt(numSe.getText());
            calculaTotal();
            numBb.setText(numEntradasBb.toString());
            if (numEntradasBb < 0) {

                numBb.setText("0");
                calculaTotal();
            }

            if (numTotal > 10) {
                numTotal -= numEntradasBb;
                numEntradasOrd = 0;
                while (numTotal < 10) {
                    numTotal += 1;
                    numEntradasBb += 1;
                }
                numBb.setText(numEntradasBb.toString());
                calculaTotal();
            }
        } catch (NumberFormatException excepcion) {
            numBb.setText("0");
            calculaTotal();
        }
    }//GEN-LAST:event_numBbFocusLost

    private void numOrdMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numOrdMouseExited
        // TODO add your handling code here:
        try {
            Integer numEntradasOrd = Integer.parseInt(numOrd.getText());
            Integer numEntradasBb = Integer.parseInt(numBb.getText());
            Integer numEntradasNi = Integer.parseInt(numNi.getText());
            Integer numEntradasEs = Integer.parseInt(numEs.getText());
            Integer numEntradasSe = Integer.parseInt(numSe.getText());
            calculaTotal();
            numOrd.setText(numEntradasOrd.toString());
            if (numEntradasOrd < 0) {

                numOrd.setText("0");
                calculaTotal();
            }

            if (numTotal > 10) {
                numTotal -= numEntradasOrd;
                numEntradasOrd = 0;
                while (numTotal < 10) {
                    numTotal += 1;
                    numEntradasOrd += 1;
                }
                numOrd.setText(numEntradasOrd.toString());
                calculaTotal();
            }
        } catch (NumberFormatException excepcion) {
            numOrd.setText("0");
            calculaTotal();
        }
    }//GEN-LAST:event_numOrdMouseExited

    private void numBbMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numBbMouseExited
        // TODO add your handling code here:
        try {
            Integer numEntradasOrd = Integer.parseInt(numOrd.getText());
            Integer numEntradasBb = Integer.parseInt(numBb.getText());
            Integer numEntradasNi = Integer.parseInt(numNi.getText());
            Integer numEntradasEs = Integer.parseInt(numEs.getText());
            Integer numEntradasSe = Integer.parseInt(numSe.getText());
            calculaTotal();
            numBb.setText(numEntradasBb.toString());
            if (numEntradasBb < 0) {

                numBb.setText("0");
                calculaTotal();
            }

            if (numTotal > 10) {
                numTotal -= numEntradasBb;
                numEntradasBb = 0;
                while (numTotal < 10) {
                    numTotal += 1;
                    numEntradasBb += 1;
                }
                numBb.setText(numEntradasBb.toString());
                calculaTotal();
            }
        } catch (NumberFormatException excepcion) {
            numBb.setText("0");
            calculaTotal();
        }
    }//GEN-LAST:event_numBbMouseExited

    private void numNiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numNiFocusLost
        // TODO add your handling code here:
        try {
            Integer numEntradasOrd = Integer.parseInt(numOrd.getText());
            Integer numEntradasBb = Integer.parseInt(numBb.getText());
            Integer numEntradasNi = Integer.parseInt(numNi.getText());
            Integer numEntradasEs = Integer.parseInt(numEs.getText());
            Integer numEntradasSe = Integer.parseInt(numSe.getText());
            calculaTotal();
            numNi.setText(numEntradasNi.toString());
            if (numEntradasNi < 0) {

                numNi.setText("0");
                calculaTotal();
            }

            if (numTotal > 10) {
                numTotal -= numEntradasNi;
                numEntradasNi = 0;
                while (numTotal < 10) {
                    numTotal += 1;
                    numEntradasNi += 1;
                }
                numNi.setText(numEntradasNi.toString());
                calculaTotal();
            }
        } catch (NumberFormatException excepcion) {
            numNi.setText("0");
            calculaTotal();
        }
    }//GEN-LAST:event_numNiFocusLost

    private void numNiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numNiMouseExited
        // TODO add your handling code here:
        try {
            Integer numEntradasOrd = Integer.parseInt(numOrd.getText());
            Integer numEntradasBb = Integer.parseInt(numBb.getText());
            Integer numEntradasNi = Integer.parseInt(numNi.getText());
            Integer numEntradasEs = Integer.parseInt(numEs.getText());
            Integer numEntradasSe = Integer.parseInt(numSe.getText());
            calculaTotal();
            numNi.setText(numEntradasNi.toString());
            if (numEntradasNi < 0) {

                numNi.setText("0");
                calculaTotal();
            }

            if (numTotal > 10) {
                numTotal -= numEntradasNi;
                numEntradasNi = 0;
                while (numTotal < 10) {
                    numTotal += 1;
                    numEntradasNi += 1;
                }
                numNi.setText(numEntradasNi.toString());
                calculaTotal();
            }
        } catch (NumberFormatException excepcion) {
            numNi.setText("0");
            calculaTotal();
        }
    }//GEN-LAST:event_numNiMouseExited

    private void numEsFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numEsFocusLost
        // TODO add your handling code here:
        try {
            Integer numEntradasOrd = Integer.parseInt(numOrd.getText());
            Integer numEntradasBb = Integer.parseInt(numBb.getText());
            Integer numEntradasNi = Integer.parseInt(numNi.getText());
            Integer numEntradasEs = Integer.parseInt(numEs.getText());
            Integer numEntradasSe = Integer.parseInt(numSe.getText());
            calculaTotal();
            numEs.setText(numEntradasEs.toString());
            if (numEntradasEs < 0) {

                numEs.setText("0");
                calculaTotal();
            }

            if (numTotal > 10) {
                numTotal -= numEntradasEs;
                numEntradasEs = 0;
                while (numTotal < 10) {
                    numTotal += 1;
                    numEntradasEs += 1;
                }
                numEs.setText(numEntradasEs.toString());
                calculaTotal();
            }
        } catch (NumberFormatException excepcion) {
            numEs.setText("0");
            calculaTotal();
        }
    }//GEN-LAST:event_numEsFocusLost

    private void numEsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numEsMouseExited
        // TODO add your handling code here:
        try {
            Integer numEntradasOrd = Integer.parseInt(numOrd.getText());
            Integer numEntradasBb = Integer.parseInt(numBb.getText());
            Integer numEntradasNi = Integer.parseInt(numNi.getText());
            Integer numEntradasEs = Integer.parseInt(numEs.getText());
            Integer numEntradasSe = Integer.parseInt(numSe.getText());
            calculaTotal();
            numEs.setText(numEntradasEs.toString());
            if (numEntradasEs < 0) {

                numEs.setText("0");
                calculaTotal();
            }

            if (numTotal > 10) {
                numTotal -= numEntradasEs;
                numEntradasEs = 0;
                while (numTotal < 10) {
                    numTotal += 1;
                    numEntradasEs += 1;
                }
                numEs.setText(numEntradasEs.toString());
                calculaTotal();
            }
        } catch (NumberFormatException excepcion) {
            numEs.setText("0");
            calculaTotal();
        }
    }//GEN-LAST:event_numEsMouseExited

    private void numSeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numSeFocusLost
        // TODO add your handling code here:
        try {
            Integer numEntradasOrd = Integer.parseInt(numOrd.getText());
            Integer numEntradasBb = Integer.parseInt(numBb.getText());
            Integer numEntradasNi = Integer.parseInt(numNi.getText());
            Integer numEntradasEs = Integer.parseInt(numEs.getText());
            Integer numEntradasSe = Integer.parseInt(numSe.getText());
            calculaTotal();
            numSe.setText(numEntradasSe.toString());
            if (numEntradasSe < 0) {

                numSe.setText("0");
                calculaTotal();
            }

            if (numTotal > 10) {
                numTotal -= numEntradasSe;
                numEntradasSe = 0;
                while (numTotal < 10) {
                    numTotal += 1;
                    numEntradasSe += 1;
                }
                numSe.setText(numEntradasSe.toString());
                calculaTotal();
            }
        } catch (NumberFormatException excepcion) {
            numSe.setText("0");
            calculaTotal();
        }
    }//GEN-LAST:event_numSeFocusLost

    private void numSeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numSeMouseExited
        // TODO add your handling code here:
        try {
            Integer numEntradasOrd = Integer.parseInt(numOrd.getText());
            Integer numEntradasBb = Integer.parseInt(numBb.getText());
            Integer numEntradasNi = Integer.parseInt(numNi.getText());
            Integer numEntradasEs = Integer.parseInt(numEs.getText());
            Integer numEntradasSe = Integer.parseInt(numSe.getText());
            calculaTotal();
            numSe.setText(numEntradasSe.toString());
            if (numEntradasSe < 0) {

                numSe.setText("0");
                calculaTotal();
            }

            if (numTotal > 10) {
                numTotal -= numEntradasSe;
                numEntradasSe = 0;
                while (numTotal < 10) {
                    numTotal += 1;
                    numEntradasSe += 1;
                }
                numSe.setText(numEntradasSe.toString());
                calculaTotal();
            }
        } catch (NumberFormatException excepcion) {
            numSe.setText("0");
            calculaTotal();
        }
    }//GEN-LAST:event_numSeMouseExited

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        fa.vistaAyuda(this);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cerrar;
    private javax.swing.JButton comprar;
    private javax.swing.JLabel dia;
    private javax.swing.ButtonGroup grupoBotones;
    private javax.swing.JLabel hora;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel masBb;
    private javax.swing.JLabel masEs;
    private javax.swing.JLabel masNi;
    private javax.swing.JLabel masOrd;
    private javax.swing.JLabel masSe;
    private javax.swing.JLabel menosBb;
    private javax.swing.JLabel menosEs;
    private javax.swing.JLabel menosNin;
    private javax.swing.JLabel menosOrd;
    private javax.swing.JLabel menosSe;
    private javax.swing.JCheckBox movRed;
    private javax.swing.JTextField numBb;
    private javax.swing.JTextField numEs;
    private javax.swing.JLabel numMax;
    private javax.swing.JTextField numNi;
    private javax.swing.JTextField numOrd;
    private javax.swing.JTextField numSe;
    private javax.swing.JLabel precBb;
    private javax.swing.JLabel precEs;
    private javax.swing.JLabel precNi;
    private javax.swing.JLabel precOrd;
    private javax.swing.JLabel precSe;
    private javax.swing.JLabel precTotal;
    private javax.swing.JLabel ruta;
    private javax.swing.JLabel txtDia;
    private javax.swing.JLabel txtHora;
    private javax.swing.JLabel txtRuta1;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables

    public void cerrar() {
        this.dispose();
        VSeleccion vs = (VSeleccion) parent;
        vs.cerrar();
    }

    public void confirmacionSalir(boolean dec) {
        if (dec) {
            this.cerrar();
        }
    }

    public void confirmacionEdad(boolean confirmacion) {
        if (confirmacion) {
            comprar();
        }
    }

}
