/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author alumnogreibd
 */
public class VMas extends javax.swing.JFrame {

    private aplicacion.FachadaAplicacion fa;

    /**
     * Creates new form VMercado
     */
    public VMas(aplicacion.FachadaAplicacion fa) {
        this.fa = fa;
        initComponents();
        falloc.setVisible(false);
        fallom.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnInicio = new javax.swing.JButton();
        btnRuta = new javax.swing.JButton();
        btnBilletes = new javax.swing.JButton();
        btnMas = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        correoUsr = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        Informacion = new javax.swing.JLabel();
        selIdiom = new javax.swing.JLabel();
        btnAyuda = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        telefono = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        mail = new javax.swing.JLabel();
        ubicacion = new javax.swing.JLabel();
        mensaje = new javax.swing.JLabel();
        correoText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        mensajeText = new javax.swing.JTextArea();
        enviar = new javax.swing.JButton();
        contactanos = new javax.swing.JLabel();
        javax.swing.JLabel email = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        fallom = new javax.swing.JLabel();
        falloc = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(390, 844));
        setResizable(false);
        setSize(new java.awt.Dimension(390, 844));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 714, 390, -1));

        jPanel2.setBackground(new java.awt.Color(153, 216, 221));
        jPanel2.setPreferredSize(new java.awt.Dimension(390, 111));

        btnInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Inicio.png"))); // NOI18N
        btnInicio.setBorderPainted(false);
        btnInicio.setContentAreaFilled(false);
        btnInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInicio.setFocusable(false);
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });

        btnRuta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/mapa.png"))); // NOI18N
        btnRuta.setBorderPainted(false);
        btnRuta.setContentAreaFilled(false);
        btnRuta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRuta.setFocusable(false);
        btnRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRutaActionPerformed(evt);
            }
        });

        btnBilletes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/billetes.png"))); // NOI18N
        btnBilletes.setBorderPainted(false);
        btnBilletes.setContentAreaFilled(false);
        btnBilletes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBilletes.setFocusable(false);
        btnBilletes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBilletesActionPerformed(evt);
            }
        });

        btnMas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Mas.png"))); // NOI18N
        btnMas.setBorderPainted(false);
        btnMas.setContentAreaFilled(false);
        btnMas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMas.setFocusable(false);
        btnMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(btnBilletes, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRuta)
                .addGap(19, 19, 19)
                .addComponent(btnMas, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnBilletes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 748, -1, 111));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/billetes.png"))); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 770, -1, -1));

        correoUsr.setBackground(new java.awt.Color(255, 255, 255));
        correoUsr.setPreferredSize(new java.awt.Dimension(390, 844));
        correoUsr.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("_____________________________________\n");
        correoUsr.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 340, 20));

        Informacion.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Informacion.setText("Información");
        correoUsr.add(Informacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 40, -1, -1));

        selIdiom.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        selIdiom.setText("Seleccionar Idioma");
        correoUsr.add(selIdiom, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        btnAyuda.setBackground(new java.awt.Color(77, 171, 171));
        btnAyuda.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnAyuda.setForeground(new java.awt.Color(255, 255, 255));
        btnAyuda.setText("  Ayuda");
        btnAyuda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnAyuda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAyuda.setFocusPainted(false);
        btnAyuda.setFocusable(false);
        btnAyuda.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAyudaActionPerformed(evt);
            }
        });
        correoUsr.add(btnAyuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 290, 40));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ingles.png"))); // NOI18N
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.setFocusable(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        correoUsr.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 80, 70));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/spain.png"))); // NOI18N
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.setFocusable(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        correoUsr.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 80, 70));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/gallego.png"))); // NOI18N
        jButton7.setBorderPainted(false);
        jButton7.setContentAreaFilled(false);
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.setFocusable(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        correoUsr.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 80, 70));

        telefono.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        telefono.setText("Teléfono: 968 182 342");
        correoUsr.add(telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ubicacion.png"))); // NOI18N
        correoUsr.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/telefono.png"))); // NOI18N
        correoUsr.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 40, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/correo.png"))); // NOI18N
        correoUsr.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));

        mail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mail.setText("navieraluscofusco@gmail.com");
        correoUsr.add(mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, -1, -1));

        ubicacion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ubicacion.setText("<html>Rúa Cardenal Rodrigo de Castro, 43. Monforte de Lemos<html>");
        correoUsr.add(ubicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, 260, -1));

        mensaje.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mensaje.setForeground(new java.awt.Color(102, 102, 102));
        mensaje.setText("Mensaje:");
        correoUsr.add(mensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 550, -1, -1));

        correoText.setBackground(new java.awt.Color(225, 232, 236));
        correoText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        correoText.setToolTipText("");
        correoText.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        correoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correoTextActionPerformed(evt);
            }
        });
        correoUsr.add(correoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 510, 240, -1));

        mensajeText.setBackground(new java.awt.Color(225, 232, 236));
        mensajeText.setColumns(20);
        mensajeText.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        mensajeText.setRows(5);
        mensajeText.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(mensajeText);

        correoUsr.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 580, 310, -1));

        enviar.setBackground(new java.awt.Color(255, 255, 255));
        enviar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        enviar.setForeground(new java.awt.Color(1, 88, 122));
        enviar.setText("Enviar");
        enviar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(1, 88, 122), 2));
        enviar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        enviar.setFocusPainted(false);
        enviar.setFocusable(false);
        enviar.setRequestFocusEnabled(false);
        enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarActionPerformed(evt);
            }
        });
        correoUsr.add(enviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 700, 90, 40));

        contactanos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        contactanos.setForeground(new java.awt.Color(102, 102, 102));
        contactanos.setText("Contáctanos");
        correoUsr.add(contactanos, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, -1, -1));

        email.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        email.setForeground(new java.awt.Color(102, 102, 102));
        email.setText("E-mail:");
        correoUsr.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, -1, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("_______________________________");
        correoUsr.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 290, -1));

        fallom.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        fallom.setForeground(new java.awt.Color(177, 0, 0));
        fallom.setText("*Mensaje vacío*");
        correoUsr.add(fallom, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 554, -1, 20));

        falloc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        falloc.setForeground(new java.awt.Color(177, 0, 0));
        falloc.setText("*Correo electrónico no válido*");
        correoUsr.add(falloc, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 530, 180, 20));

        getContentPane().add(correoUsr, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBilletesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBilletesActionPerformed
        // TODO add your handling code here:
        fa.vistaBilletes();
        this.dispose();
    }//GEN-LAST:event_btnBilletesActionPerformed

    private void btnRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRutaActionPerformed
        // TODO add your handling code here:
        fa.vistaRutas();
        this.dispose();
    }//GEN-LAST:event_btnRutaActionPerformed

    private void btnMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasActionPerformed
        
       
    }//GEN-LAST:event_btnMasActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        // TODO add your handling code here:
        fa.vistaInicio();
        this.dispose();
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAyudaActionPerformed
        // TODO add your handling code here:
        fa.vistaAyuda(this);
        this.setVisible(false);
    }//GEN-LAST:event_btnAyudaActionPerformed

    private void correoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correoTextActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        Informacion.setText("Información");
        selIdiom.setText("Seleccionar Idioma");
        btnAyuda.setText("  Ayuda");
        telefono.setText("Teléfono: 986 123 456");
        contactanos.setText("Contáctanos");
        mensaje.setText("Mensaje");
        enviar.setText("Enviar");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        Informacion.setText("Información");
        selIdiom.setText("Seleccionar o Idioma");
        btnAyuda.setText("  Axuda");
        telefono.setText("Teléfono: 986 123 456");
        contactanos.setText("Contáctanos");
        mensaje.setText("Mensaxe");
        enviar.setText("Enviar");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Informacion.setText("Information");
        selIdiom.setText("Choose your lenguage");
        btnAyuda.setText("  Help");
        telefono.setText("Phone Number: 986 123 456");
        contactanos.setText("Contact us");
        mensaje.setText("Message");
        enviar.setText("Send");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarActionPerformed
        // TODO add your handling code here:
        
        if (correoText.getText().isEmpty()) 
            falloc.setVisible(true);
        else 
            falloc.setVisible(false);
        if (mensajeText.getText().isEmpty()) 
            fallom.setVisible(true);
         else 
            fallom.setVisible(false);
        
        if(!correoText.getText().isEmpty() && !mensajeText.getText().isEmpty()){
            Pattern pattern = Pattern.compile("^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$");
            Matcher mather = pattern.matcher(correoText.getText());
            if (mather.find() == false) {
                falloc.setVisible(true);
            } else {
                fa.muestraMensaje(this, "Mensaje enviado correctamente");
                mensajeText.setText("");
                correoText.setText("");
            }
        }  
    }//GEN-LAST:event_enviarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Informacion;
    private javax.swing.JButton btnAyuda;
    private javax.swing.JButton btnBilletes;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnMas;
    private javax.swing.JButton btnRuta;
    private javax.swing.JLabel contactanos;
    private javax.swing.JTextField correoText;
    private javax.swing.JPanel correoUsr;
    private javax.swing.JButton enviar;
    private javax.swing.JLabel falloc;
    private javax.swing.JLabel fallom;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mail;
    private javax.swing.JLabel mensaje;
    private javax.swing.JTextArea mensajeText;
    private javax.swing.JLabel selIdiom;
    private javax.swing.JLabel telefono;
    private javax.swing.JLabel ubicacion;
    // End of variables declaration//GEN-END:variables

}
