/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Color;
import java.awt.Dimension;
import static java.awt.image.ImageObserver.HEIGHT;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JLabel;


public class VRuta2Info extends javax.swing.JFrame {

    private aplicacion.FachadaAplicacion fa;
    private java.awt.Frame parent;
    private int iconoCount = 0;
    private java.util.List<JLabel> vFotos;
    /**
     * Creates new form VMercado
     */
    public VRuta2Info(aplicacion.FachadaAplicacion fa, java.awt.Frame parent) {
        this.fa = fa;
        this.parent = parent;
        initComponents();
        this.vFotos = new ArrayList<>();
        vFotos.add(fotos);
        vFotos.add(fotos1);
        vFotos.add(fotos2);
        vFotos.add(fotos3);
        vFotos.add(fotos4);
        vFotos.add(fotos5);
        this.jScrollPane1.getVerticalScrollBar().setPreferredSize(new Dimension(13,HEIGHT));
        this.jScrollPane1.getVerticalScrollBar().setBackground(new Color(67,78,80));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnInicio = new javax.swing.JButton();
        btnRuta = new javax.swing.JButton();
        btnBilletes = new javax.swing.JButton();
        btnMas = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        volver = new javax.swing.JButton();
        btnIzquierda = new javax.swing.JButton();
        btnDerecha = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane3 = new javax.swing.JTextPane();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextPane4 = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextPane5 = new javax.swing.JTextPane();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextPane6 = new javax.swing.JTextPane();
        jLabel8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fotos = new javax.swing.JLabel();
        fotos1 = new javax.swing.JLabel();
        fotos2 = new javax.swing.JLabel();
        fotos3 = new javax.swing.JLabel();
        fotos4 = new javax.swing.JLabel();
        fotos5 = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(390, 844));
        setResizable(false);
        setSize(new java.awt.Dimension(390, 844));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 714, 390, -1));

        jPanel2.setBackground(new java.awt.Color(153, 216, 221));
        jPanel2.setPreferredSize(new java.awt.Dimension(390, 111));

        btnInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Inicio.png"))); // NOI18N
        btnInicio.setBorderPainted(false);
        btnInicio.setContentAreaFilled(false);
        btnInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInicio.setFocusable(false);
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });

        btnRuta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/mapa.png"))); // NOI18N
        btnRuta.setBorderPainted(false);
        btnRuta.setContentAreaFilled(false);
        btnRuta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRuta.setFocusable(false);
        btnRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRutaActionPerformed(evt);
            }
        });

        btnBilletes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/billetes.png"))); // NOI18N
        btnBilletes.setBorderPainted(false);
        btnBilletes.setContentAreaFilled(false);
        btnBilletes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBilletes.setFocusable(false);
        btnBilletes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBilletesActionPerformed(evt);
            }
        });

        btnMas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Mas.png"))); // NOI18N
        btnMas.setBorderPainted(false);
        btnMas.setContentAreaFilled(false);
        btnMas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMas.setFocusable(false);
        btnMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(btnBilletes, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRuta)
                .addGap(19, 19, 19)
                .addComponent(btnMas, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnBilletes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 748, -1, 111));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/billetes.png"))); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 770, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(390, 844));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/volver.png"))); // NOI18N
        volver.setBorderPainted(false);
        volver.setContentAreaFilled(false);
        volver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        volver.setFocusable(false);
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        jPanel3.add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 40, -1));

        btnIzquierda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Izquierda.png"))); // NOI18N
        btnIzquierda.setBorderPainted(false);
        btnIzquierda.setContentAreaFilled(false);
        btnIzquierda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIzquierda.setFocusPainted(false);
        btnIzquierda.setFocusable(false);
        btnIzquierda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzquierdaActionPerformed(evt);
            }
        });
        jPanel3.add(btnIzquierda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 40, 30));

        btnDerecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Derecha.png"))); // NOI18N
        btnDerecha.setBorderPainted(false);
        btnDerecha.setContentAreaFilled(false);
        btnDerecha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDerecha.setFocusPainted(false);
        btnDerecha.setFocusable(false);
        btnDerecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDerechaActionPerformed(evt);
            }
        });
        jPanel3.add(btnDerecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 40, 37));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(16, 137, 177));
        jLabel2.setText("Descripción");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jTextPane1.setEditable(false);
        jTextPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(16, 137, 177), 2));
        jTextPane1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextPane1.setText("\nEsta ruta en catamarán recorre el río Miño desde el pueblo de Belesar, navegando sobre aldeas sumergidas tras la construcción del embalse de Os Peares y bordeando el impresionante meandro que forma el “Cabo do Mundo”, uno de los lugares más emblemáticos de la Ribeira Sacra. Desde la embarcación podremos observar en ambos márgenes del río frondosas masas de bosques, junto con el característico paisaje de viñedos cultivados en terrazas, entre las que se asoman algunas iglesias, pueblos de gran belleza y también lugares destacados como la Playa de A Cova.\n\nEn las proximidades de esta ruta se pueden visitar bodegas, hacer senderismo, acercarse hasta la villa de Chantada o conocer los secretos mejor guardados del románico rural a través de las singulares iglesias da contorna.");
        jScrollPane2.setViewportView(jTextPane1);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 327, 300));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(16, 137, 177));
        jLabel3.setText("Recorrido");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        jTextPane2.setEditable(false);
        jTextPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(16, 137, 177), 2));
        jTextPane2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextPane2.setText("\n  - La ruta comienza en el embarcadero del pueblo Belesar (provincia de Lugo)\n\n  - Paso a través del puente de Portotide\n\n  - Vista del famoso Cabo do Mundo \n\n  - Se continuará el río por el Castro de Macre\n\n  - Se volverá río arriba hasta el Embarcadero de Maiorga\n");
        jTextPane2.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jScrollPane3.setViewportView(jTextPane2);

        jPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 327, 190));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(16, 137, 177));
        jLabel4.setText("Duración");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 630, -1, -1));

        jTextPane3.setEditable(false);
        jTextPane3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(16, 137, 177), 2));
        jTextPane3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextPane3.setText("  \n 2 horas aproximadamente");
        jScrollPane4.setViewportView(jTextPane3);

        jPanel4.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 660, 327, 50));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(16, 137, 177));
        jLabel5.setText("Localización");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 880, -1, -1));

        jTextPane4.setEditable(false);
        jTextPane4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(16, 137, 177), 2));
        jTextPane4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextPane4.setText("\nLa ruta comenzará en el Embarcadero del pueblo de Balsar, Lugo.\n\n - Dirección: Embarcadero de Belesar, LU-P-1804, 111, 27548 Belesar, Lugo\n\n - Coordenadas: 42.5936¡, -7.7254");
        jScrollPane5.setViewportView(jTextPane4);

        jPanel4.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 920, 327, 140));

        jTextPane5.setEditable(false);
        jTextPane5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(16, 137, 177), 2));
        jTextPane5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextPane5.setText("\n  Billetes con tarifa de Grupo: 13€\n\n  Billetes individuales:\n\n  - Ordinario:\t\t20€\n  - Bebés (0-3 años):\tGratis\n  - Niños (4-12 años):\t13€\n  - Estudiantes: \t16€\n  - Seniors ( > 60 años):\t13€"); // NOI18N
        jScrollPane6.setViewportView(jTextPane5);

        jPanel4.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 1110, 327, 170));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(16, 137, 177));
        jLabel6.setText("Tarifas");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 1070, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("*Todo menor de edad deberá estar acompañado de un adulto*");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 1290, -1, -1));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 1310, 260, 30));

        jTextPane6.setEditable(false);
        jTextPane6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(16, 137, 177), 2));
        jTextPane6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextPane6.setText("\n  Todos los días de la semana. \n  Horarios:\t- 9:00\n\t-12:00\n\t-17:00 ");
        jScrollPane7.setViewportView(jTextPane6);

        jPanel4.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 760, 327, 100));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(16, 137, 177));
        jLabel8.setText("Horarios");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 730, -1, -1));

        jScrollPane1.setViewportView(jPanel4);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 390, 450));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ruta Cabo do Mundo");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 100));

        fotos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fotos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cabo2.png"))); // NOI18N
        jPanel3.add(fotos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 390, 200));

        fotos1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cabo3.png"))); // NOI18N
        jPanel3.add(fotos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, 200));

        fotos2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cabo4.png"))); // NOI18N
        jPanel3.add(fotos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, 200));

        fotos3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cabo5.png"))); // NOI18N
        jPanel3.add(fotos3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, 200));

        fotos4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cabo6.png"))); // NOI18N
        jPanel3.add(fotos4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, 200));

        fotos5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cabo7.png"))); // NOI18N
        jPanel3.add(fotos5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, 200));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBilletesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBilletesActionPerformed
        // TODO add your handling code here:
        fa.vistaBilletes();
        this.dispose();
    }//GEN-LAST:event_btnBilletesActionPerformed

    private void btnRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRutaActionPerformed
        // TODO add your handling code here:
        fa.vistaRutas();
        this.dispose();
    }//GEN-LAST:event_btnRutaActionPerformed

    private void btnMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasActionPerformed
        // TODO add your handling code here:
        fa.vistaMas();
        this.dispose();
    }//GEN-LAST:event_btnMasActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        // TODO add your handling code here:
        fa.vistaInicio();
        this.dispose();
    }//GEN-LAST:event_btnInicioActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        // TODO add your handling code here:
        this.cerrar();
    }//GEN-LAST:event_volverActionPerformed

    private void btnIzquierdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzquierdaActionPerformed
        // TODO add your handling code here:
        iconoCount = iconoCount - 1;
        if (iconoCount < 0) {
            iconoCount=vFotos.size()-1;
            for (JLabel x : vFotos){
                x.setVisible(false);
            }
            vFotos.get(iconoCount).setVisible(true);
        }else{
            vFotos.get(iconoCount).setVisible(true);
        }
    }//GEN-LAST:event_btnIzquierdaActionPerformed

    private void btnDerechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDerechaActionPerformed
        // TODO add your handling code here:
        iconoCount = iconoCount + 1;
        if (iconoCount == vFotos.size()) {
            for (JLabel x : vFotos){
                x.setVisible(true);
            }
            iconoCount=0;
        }else{
            vFotos.get(iconoCount-1).setVisible(false);
        }
    }//GEN-LAST:event_btnDerechaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBilletes;
    private javax.swing.JButton btnDerecha;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnIzquierda;
    private javax.swing.JButton btnMas;
    private javax.swing.JButton btnRuta;
    private javax.swing.JLabel fotos;
    private javax.swing.JLabel fotos1;
    private javax.swing.JLabel fotos2;
    private javax.swing.JLabel fotos3;
    private javax.swing.JLabel fotos4;
    private javax.swing.JLabel fotos5;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JTextPane jTextPane3;
    private javax.swing.JTextPane jTextPane4;
    private javax.swing.JTextPane jTextPane5;
    private javax.swing.JTextPane jTextPane6;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables

    
    public void cerrar(){
        this.dispose();
        this.parent.setVisible(true);
    }
}
