/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

public class VRuta1Info extends javax.swing.JFrame {

    private aplicacion.FachadaAplicacion fa;
    private java.awt.Frame parent;
    private int iconoCount = 0;
    private java.util.List<JLabel> vFotos;

    public VRuta1Info(aplicacion.FachadaAplicacion fa, java.awt.Frame parent) throws IOException {
        this.fa = fa;
        this.parent = parent;
        initComponents();
        this.vFotos = new ArrayList<>();
        Icon f = fotos.getIcon();

        vFotos.add(fotos);
        vFotos.add(fotos1);
        vFotos.add(fotos2);
        vFotos.add(fotos3);
        vFotos.add(fotos4);
        vFotos.add(fotos5);
        vFotos.add(fotos6);

        this.jScrollPane1.getVerticalScrollBar().setPreferredSize(new Dimension(13, HEIGHT));
        this.jScrollPane1.getVerticalScrollBar().setBackground(new Color(67, 78, 80));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnInicio = new javax.swing.JButton();
        btnRuta = new javax.swing.JButton();
        btnBilletes = new javax.swing.JButton();
        btnMas = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        volver = new javax.swing.JButton();
        btnDerecha1 = new javax.swing.JButton();
        btnIzquierda1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane3 = new javax.swing.JTextPane();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextPane4 = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextPane5 = new javax.swing.JTextPane();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextPane6 = new javax.swing.JTextPane();
        jLabel8 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fotos = new javax.swing.JLabel();
        fotos1 = new javax.swing.JLabel();
        fotos2 = new javax.swing.JLabel();
        fotos3 = new javax.swing.JLabel();
        fotos4 = new javax.swing.JLabel();
        fotos5 = new javax.swing.JLabel();
        fotos6 = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(390, 844));
        setResizable(false);
        setSize(new java.awt.Dimension(390, 844));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 714, 390, -1));

        jPanel2.setBackground(new java.awt.Color(153, 216, 221));
        jPanel2.setPreferredSize(new java.awt.Dimension(390, 111));

        btnInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Inicio.png"))); // NOI18N
        btnInicio.setBorderPainted(false);
        btnInicio.setContentAreaFilled(false);
        btnInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInicio.setFocusable(false);
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });

        btnRuta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/mapa.png"))); // NOI18N
        btnRuta.setBorderPainted(false);
        btnRuta.setContentAreaFilled(false);
        btnRuta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRuta.setFocusable(false);
        btnRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRutaActionPerformed(evt);
            }
        });

        btnBilletes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/billetes.png"))); // NOI18N
        btnBilletes.setBorderPainted(false);
        btnBilletes.setContentAreaFilled(false);
        btnBilletes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBilletes.setFocusable(false);
        btnBilletes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBilletesActionPerformed(evt);
            }
        });

        btnMas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Mas.png"))); // NOI18N
        btnMas.setBorderPainted(false);
        btnMas.setContentAreaFilled(false);
        btnMas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMas.setFocusable(false);
        btnMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(btnBilletes, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRuta)
                .addGap(19, 19, 19)
                .addComponent(btnMas, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnBilletes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 748, -1, 111));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/billetes.png"))); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 770, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(390, 844));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/volver.png"))); // NOI18N
        volver.setBorderPainted(false);
        volver.setContentAreaFilled(false);
        volver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        volver.setFocusable(false);
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        jPanel3.add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 40, -1));

        btnDerecha1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Derecha.png"))); // NOI18N
        btnDerecha1.setBorderPainted(false);
        btnDerecha1.setContentAreaFilled(false);
        btnDerecha1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDerecha1.setFocusPainted(false);
        btnDerecha1.setFocusable(false);
        btnDerecha1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDerecha1ActionPerformed(evt);
            }
        });
        jPanel3.add(btnDerecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 40, 37));

        btnIzquierda1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Izquierda.png"))); // NOI18N
        btnIzquierda1.setBorderPainted(false);
        btnIzquierda1.setContentAreaFilled(false);
        btnIzquierda1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIzquierda1.setFocusPainted(false);
        btnIzquierda1.setFocusable(false);
        btnIzquierda1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzquierda1ActionPerformed(evt);
            }
        });
        jPanel3.add(btnIzquierda1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 40, 30));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(16, 137, 177));
        jLabel2.setText("Descripción");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jTextPane1.setEditable(false);
        jTextPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(16, 137, 177), 2));
        jTextPane1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextPane1.setText("\nEsta ruta en catamarán atraviesa el corazón de la Ribeira Sacra por el Cañón do Sil desde el embarcadero de la Diputación de Lugo- Ponte do Sil (Municipio de Monforte de Lemos) hasta el entorno del Monasterio de Santa Cristina de Ribas de Sil. Un recorrido panorámico imprescindible que nos permitirá conocer lo más esencial de la Ribeira Sacra y de su viticultura heroica, así como contemplar el espectacular desfiladero que forma el Cañón del Sil en su tramo de mayor verticalidad.\n\nEn las proximidades de esta ruta se pueden visitar bodegas, impresionantes miradores, iglesias románicas, la ciudad de Monforte de Lemos o la tradicional alfarería de Gundivós, que completarán un viaje inolvidable.");
        jScrollPane2.setViewportView(jTextPane1);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 327, 250));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(16, 137, 177));
        jLabel3.setText("Recorrido");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        jTextPane2.setEditable(false);
        jTextPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(16, 137, 177), 2));
        jTextPane2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextPane2.setText("\n  - La ruta comienza en el Embarcadero de la Deputación de Lugo Ponte do Sil (Municipio de Monforte de Lemos) \n\n  - Paso por enfrente de las bodegas y viñedos de A Costrela\n\n  - Se adentrará en los cañones, pasando por el Monasterio de Santa Cristina de Ribas de Sil\n\n  - Se continuará por el Encoro de Santo Estevo a través de los miradores y altos acantilados\n\n  - Fin de la ruta en el embarcadeor de Santo Estevo. \n");
        jTextPane2.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jScrollPane3.setViewportView(jTextPane2);

        jPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 327, 240));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(16, 137, 177));
        jLabel4.setText("Duración");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 630, -1, -1));

        jTextPane3.setEditable(false);
        jTextPane3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(16, 137, 177), 2));
        jTextPane3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextPane3.setText("\n  1 hora 45 minutos aproximadamente");
        jScrollPane4.setViewportView(jTextPane3);

        jPanel4.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 660, 327, 50));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(16, 137, 177));
        jLabel5.setText("Localización");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 880, -1, -1));

        jTextPane4.setEditable(false);
        jTextPane4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(16, 137, 177), 2));
        jTextPane4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextPane4.setText("\nLa ruta comenzará en el Embarcadero de la Deputación de Lugo Ponte do Sil.\n\n - Dirección: Ponte do Sil, 27329, Lugo\n\n - Coordenadas: 42.4721, -7.2850");
        jScrollPane5.setViewportView(jTextPane4);

        jPanel4.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 920, 327, 130));

        jTextPane5.setEditable(false);
        jTextPane5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(16, 137, 177), 2));
        jTextPane5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextPane5.setText("\n  Billetes con tarifa de Grupo: 10€\n\n  Billetes individuales:\n\n  - Ordinario: \t17€\n  - Bebés (0-3 años):\tGratis\n  - Niños (4-12 años):\t10€\n  - Estudiantes: \t13€\n  - Seniors ( > 60 años):\t10€"); // NOI18N
        jScrollPane6.setViewportView(jTextPane5);

        jPanel4.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 1110, 327, 170));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(16, 137, 177));
        jLabel6.setText("Tarifas");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 1070, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("*Todo menor de edad deberá estar acompañado de un adulto*");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 1290, -1, -1));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 1310, 290, 30));

        jTextPane6.setEditable(false);
        jTextPane6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(16, 137, 177), 2));
        jTextPane6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextPane6.setText("\n  Todos los días de la semana. \n  Horarios:\t- 9:00\n\t-12:00\n\t-17:00 ");
        jScrollPane7.setViewportView(jTextPane6);

        jPanel4.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 760, 327, 100));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(16, 137, 177));
        jLabel8.setText("Horarios");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 730, -1, -1));

        jScrollPane1.setViewportView(jPanel4);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 390, 450));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Ruta por el Cañon del Sil");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(27, 27, 27))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(29, 29, 29))
        );

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 100));

        fotos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fotos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sil2.png"))); // NOI18N
        jPanel3.add(fotos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 390, 200));

        fotos1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sil3.png"))); // NOI18N
        jPanel3.add(fotos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, 200));

        fotos2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sil4.png"))); // NOI18N
        jPanel3.add(fotos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, 200));

        fotos3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sil8.png"))); // NOI18N
        jPanel3.add(fotos3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, 200));

        fotos4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sil5.png"))); // NOI18N
        jPanel3.add(fotos4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, 200));

        fotos5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sil7.png"))); // NOI18N
        jPanel3.add(fotos5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, 200));

        fotos6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sil6.png"))); // NOI18N
        jPanel3.add(fotos6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 390, 200));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBilletesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBilletesActionPerformed
        // TODO add your handling code here:
        fa.vistaBilletes();
        this.dispose();
        this.parent.dispose();
    }//GEN-LAST:event_btnBilletesActionPerformed

    private void btnRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRutaActionPerformed
        // TODO add your handling code here:
        fa.vistaRutas();
        this.dispose();
        this.parent.dispose();
    }//GEN-LAST:event_btnRutaActionPerformed

    private void btnMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasActionPerformed
        // TODO add your handling code here:
        fa.vistaMas();
        this.dispose();
        this.parent.dispose();
    }//GEN-LAST:event_btnMasActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        // TODO add your handling code here:
        fa.vistaInicio();
        this.dispose();
        this.parent.dispose();
    }//GEN-LAST:event_btnInicioActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        // TODO add your handling code here:
        this.cerrar();
    }//GEN-LAST:event_volverActionPerformed

    private void btnDerecha1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDerecha1ActionPerformed
        // TODO add your handling code here:
        iconoCount = iconoCount + 1;
        if (iconoCount == vFotos.size()) {
            for (JLabel x : vFotos){
                x.setVisible(true);
            }
            iconoCount=0;
        }else{
            vFotos.get(iconoCount-1).setVisible(false);
        }
    }//GEN-LAST:event_btnDerecha1ActionPerformed

    private void btnIzquierda1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzquierda1ActionPerformed
        // TODO add your handling code here:
        iconoCount = iconoCount - 1;
        if (iconoCount < 0) {
            iconoCount=vFotos.size()-1;
            for (JLabel x : vFotos){
                x.setVisible(false);
            }
            vFotos.get(iconoCount).setVisible(true);
        }else{
            vFotos.get(iconoCount).setVisible(true);
        }
    }//GEN-LAST:event_btnIzquierda1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBilletes;
    private javax.swing.JButton btnDerecha1;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnIzquierda1;
    private javax.swing.JButton btnMas;
    private javax.swing.JButton btnRuta;
    private javax.swing.JLabel fotos;
    private javax.swing.JLabel fotos1;
    private javax.swing.JLabel fotos2;
    private javax.swing.JLabel fotos3;
    private javax.swing.JLabel fotos4;
    private javax.swing.JLabel fotos5;
    private javax.swing.JLabel fotos6;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JTextPane jTextPane3;
    private javax.swing.JTextPane jTextPane4;
    private javax.swing.JTextPane jTextPane5;
    private javax.swing.JTextPane jTextPane6;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables

    public void cerrar() {
        this.dispose();
        this.parent.setVisible(true);
    }
}
